# -*- coding: utf-8 -*-
"""
Universo ticker — Robot Trader 2026
Azioni: 3072 | ETF: 1132 | Fondi: 781
Recuperato automaticamente dal .pyc il 08/06/2026
"""


USA_SP500 = ['AAPL', 'MSFT', 'NVDA', 'AMZN', 'GOOGL', 'GOOG', 'META', 'TSLA', 'AVGO', 'LLY', 'UNH', 'XOM', 'JPM', 'V', 'JNJ', 'PG', 'MA', 'HD', 'CVX', 'MRK', 'COST', 'ABBV', 'KO', 'ADBE', 'PEP', 'TMO', 'CRM', 'NFLX', 'MCD', 'CSCO', 'ACN', 'LIN', 'ABT', 'WMT', 'AMD', 'DHR', 'PM', 'NEE', 'TXN', 'ORCL', 'DIS', 'CMCSA', 'INTC', 'VZ', 'WFC', 'UPS', 'COP', 'MS', 'HON', 'LOW', 'UNP', 'BA', 'NKE', 'INTU', 'CAT', 'IBM', 'RTX', 'GE', 'QCOM', 'DE', 'BKNG', 'AMGN', 'ELV', 'SBUX', 'GS', 'AXP', 'BLK', 'SPGI', 'MDLZ', 'SYK', 'GILD', 'T', 'ADP', 'PLD', 'ADI', 'TJX', 'LRCX', 'AMT', 'CVS', 'CI', 'VRTX', 'REGN', 'ISRG', 'C', 'MO', 'ZTS', 'PGR', 'SO', 'BSX', 'TMUS', 'AMAT', 'BDX', 'ETN', 'SCHW', 'DUK', 'CB', 'MU', 'EOG', 'PNC', 'NOC', 'CL', 'ITW', 'BMY', 'USB', 'CME', 'APD', 'ICE', 'HCA', 'PYPL', 'SLB', 'MCO', 'AON', 'WM', 'EQIX', 'EMR', 'NSC', 'FCX', 'EL', 'SHW', 'GM', 'ORLY', 'MAR', 'GD', 'TGT', 'PSX', 'TT', 'AJG', 'MCK', 'KLAC', 'SNPS', 'MSI', 'APH', 'ADSK', 'NXPI', 'CARR', 'PCAR', 'AIG', 'SPG', 'MSCI', 'AZO', 'HUM', 'AFL', 'SYY', 'TEL', 'ECL', 'F', 'CMG', 'TDG', 'JCI', 'PSA', 'O', 'ROP', 'NEM', 'AEP', 'TRV', 'DLR', 'PAYX', 'FIS', 'KMB', 'CTVA', 'WELL', 'MET', 'ALL', 'CCI', 'ROST', 'GIS', 'D', 'PRU', 'CNC', 'HSY', 'ODFL', 'BK', 'CHTR', 'FTNT', 'KDP', 'IDXX', 'DD', 'CTAS', 'WMB', 'A', 'YUM', 'CDNS', 'KMI', 'FAST', 'OXY', 'AMP', 'EA', 'AME', 'HLT', 'RSG', 'EXC', 'IT', 'MNST', 'PEG', 'CPRT', 'KR', 'DHI', 'VRSK', 'OTIS', 'RMD', 'ROK', 'EW', 'LHX', 'LVS', 'CTSH', 'DAL', 'STZ', 'KHC', 'URI', 'GWW', 'KEYS', 'DOV', 'DXCM', 'CEG', 'FANG', 'CBRE', 'IQV', 'LH', 'VMC', 'PCG', 'DVN', 'EXR', 'XEL', 'MLM', 'HIG', 'VICI', 'ED', 'PPG', 'BKR', 'GLW', 'MTD', 'ETR', 'FTV', 'VLO', 'FITB', 'IR', 'BIIB', 'ENPH', 'MPWR', 'LYB', 'AWK', 'AEE', 'ES', 'HBAN', 'ALGN', 'TROW', 'INVH', 'BR', 'WAB', 'EFX', 'EIX', 'NTRS', 'FE', 'CDW', 'TDY', 'HPQ', 'EPAM', 'CAH', 'TTWO', 'MKC', 'WEC', 'MTB', 'DTE', 'RF', 'CFG', 'FDS', 'ZBH', 'IFF', 'BALL', 'STT', 'WBD', 'GPC', 'NUE', 'PFG', 'MOH', 'DGX', 'WY', 'EXPE', 'LEN', 'AVB', 'NDAQ', 'SWKS', 'OMC', 'WST', 'DOC', 'ARE', 'POOL', 'DRI', 'CBOE', 'SYF', 'TYL', 'EQR', 'CINF', 'AES', 'TER', 'UAL', 'TECH', 'PKG', 'COF', 'LUV', 'LDOS', 'BBY', 'APTV', 'KEY', 'AMCR', 'JBHT', 'DLTR', 'NTAP', 'STE', 'IP', 'IRM', 'EBAY', 'AKAM', 'TSCO', 'CAG', 'STLD', 'J', 'ZBRA', 'BLDR', 'JKHY', 'MAA', 'SWK', 'EXPD', 'ULTA', 'HPE', 'WRB', 'EVRG', 'HRL', 'UDR', 'WAT', 'VTRS', 'TFX', 'TRGP', 'CE', 'ESS', 'CPT', 'LW', 'CLX', 'CHRW', 'HST', 'PAYC', 'DG', 'INCY', 'FICO', 'PTC', 'ATO', 'CPB', 'BXP', 'FOXA', 'FOX', 'CMS', 'BIO', 'VRSN', 'ROL', 'NVR', 'CCL', 'PODD', 'LKQ', 'NDSN', 'HSIC', 'LNT', 'MOS', 'KIM', 'REG', 'GNRC', 'FRT', 'AIZ', 'TAP', 'RHI', 'BEN', 'EMN', 'PNR', 'RJF', 'NI', 'AOS', 'BWA', 'IEX', 'WHR', 'MKTX', 'ALLE', 'HII', 'HAS', 'ZION', 'AAP', 'GL', 'VFC', 'FFIV', 'WYNN', 'ALB', 'NWSA', 'NWS', 'AA', 'UBER', 'ABNB', 'CRWD', 'DELL', 'PLTR', 'GEV', 'APP', 'AXON', 'ANET', 'PANW', 'DPZ', 'NCLH', 'RCL', 'MGM', 'LULU', 'DECK', 'AVTR', 'GRMN', 'VLTO', 'KVUE', 'SMCI', 'SOLV', 'EG', 'TXRH', 'WSM', 'ELF', 'BLDR', 'GDDY', 'PWR', 'CEG']

USA_MIDCAP = ['WTFC', 'WBS', 'BOH', 'CBSH', 'WSFS', 'FFIN', 'GBCI', 'FNB', 'SFBS', 'HLI', 'HLNE', 'STEP', 'AXS', 'RLI', 'SIGI', 'KMPR', 'STWD', 'SFNC', 'MMSI', 'OMCL', 'ACAD', 'NVST', 'MEDP', 'HALO', 'IRTC', 'AGIO', 'EME', 'MATX', 'KNX', 'SAIA', 'LII', 'HXL', 'BCPC', 'TREX', 'AWI', 'AAON', 'GATX', 'HRI', 'REXR', 'SFM', 'BOOT', 'FIVE', 'EAT', 'WING', 'CHEF', 'CAKE', 'TXRH', 'BURL', 'DKS', 'MANH', 'SANM', 'BOX', 'NOVT', 'PCTY', 'GTLB', 'MLAB', 'NNN', 'STAG', 'SKT', 'ELS', 'NHI', 'OHI', 'EPR', 'COLD', 'SAFE', 'SM', 'CHRD', 'AROC', 'SBR', 'CMC', 'CRS', 'SLVM', 'NJR', 'MGEE', 'AWR', 'MP', 'PLNT', 'RBC', 'SNX', 'INGR', 'UFPI', 'WMS', 'RUSHA', 'DINO']

USA_RUSSELL2000 = [ 'AFBI', 'AKR', 'ALCO', 'ALTO', 'ANIP', 'AOSL', 'AQST', 'ARDC', 'ARQT', 'ASRT', 'ATXG', 'AVAV', 'AVPT', 'AVXL', 'AZTA', 'BCAL', 'BCBP', 'BCML', 'BCOW', 'BFH', 'BFS', 'BKSC', 'BNCC', 'BPOP', 'BRLT', 'BRSP', 'BWFG', 'BYFC', 'CBFV', 'CFBK', 'CFFN', 'CGEN', 'CLBK', 'COLB', 'COLL', 'CPF', 'CPS', 'CPSS', 'CZWI', 'DBRG', 'DCBO', 'DFIN', 'DLNG', 'DLTH', 'DXPE', 'EGHT', 'ELAN', 'ELME', 'EMBC', 'ENOV', 'EWBC', 'FNWB', 'FTDR', 'FURY', 'GCMG', 'GIPR', 'GKOS', 'GRFS', 'GRPN', 'GTIM', 'HARL', 'HASI', 'HCKT', 'HIFS', 'HIT', 'HNRG', 'HQH', 'IDCC', 'IDYA', 'IMCV', 'INDB', 'INTA', 'IPIX', 'JPC', 'JRSH', 'JSPR', 'KMT', 'KRG', 'LCII', 'LPX', 'LVWR', 'LXP', 'MAXN', 'MDGL', 'MGAM', 'MGNX', 'MGTX', 'MKSI', 'MLCO', 'MNR', 'MORN', 'MRCY', 'MSTR', 'MTG', 'MTN', 'MUR', 'NBR', 'NCSM', 'NSA', 'NSP', 'NTST', 'NVAX', 'NWPX', 'NXG', 'OGN', 'OHI', 'OLED', 'OMAB', 'OMF', 'ONEW', 'ONL', 'ORGO', 'ORLA', 'OVID', 'PANL', 'PMT', 'PPSI', 'PRST', 'PRT', 'QDEL', 'QLYS', 'QRHC', 'RAIL', 'REZI', 'REXR', 'RIVN', 'RKT', 'RMBI', 'RMCF', 'RMNI', 'RPRX', 'RRC', 'RRBI', 'RRR', 'RRTS', 'RSSS', 'RUN', 'SBFG', 'SBGI', 'SEER', 'SGHT', 'SIG', 'SLG', 'SM', 'SONX', 'SSBI', 'SST', 'STGW', 'STOK', 'STRS', 'SUPX', 'SWIM', 'SYRE', 'TBPH', 'TDI', 'TIPT', 'TVC', 'UGI', 'ULBI', 'UMBF', 'URBN', 'URNM', 'USFD', 'VCNX', 'VECO', 'VEON', 'VERA', 'VITL', 'VNET', 'VNRX', 'VSAT', 'VVOS', 'WBHC', 'WCLD', 'WOLF', 'WORX', 'WTFC', 'WULF', 'WWR', 'YELP', 'ADAG', 'ADIL', 'ADTN', 'ADTX', 'ADXN', 'AEHR', 'AGIO', 'AIRG', 'AKBA', 'ALAR', 'ALDX', 'ALEC', 'ALUR', 'ANIK', 'ANIP', 'ARAY', 'ARRY', 'ATXG', 'AUID', 'AVXL', 'BBIO', 'BCYC', 'BFRI', 'BHVN', 'BJDX', 'BKKT', 'BLTE', 'BMEA', 'BNGO', 'BNTX', 'BRGX', 'BRTX', 'CABA', 'CARE', 'CCCC', 'CCRN', 'CGEM', 'CGON', 'CLDX', 'CLGN', 'CLNN', 'CLPS', 'CLRB', 'CLSD', 'CLVT', 'COCP', 'CODX', 'CORT', 'CPRX', 'CRBP', 'CRDF', 'CRIS', 'CRNX', 'CTMX', 'CTSO', 'CURV', 'CVKD', 'CXAI', 'CYCN', 'DCTH', 'DERM', 'DMAC', 'DNLI', 'DNUT', 'DOCN', 'DSGX', 'DTIL', 'DTSS', 'DXLG', 'ECVT', 'EDBL', 'EDIT', 'EDSA', 'EGRX', 'EINC', 'ELAN', 'ELVN', 'ENLV', 'ENTG', 'ENVB', 'EOLS', 'ERAS', 'ERNA', 'ESPR', 'EVAX', 'EVFM', 'EVGO', 'EVGN', 'EVLO', 'EVTL', 'EXEL', 'EXLS', 'EYEG', 'EYPT', 'FATE', 'FBIO', 'FBRX', 'FCRS', 'FDMT', 'FKWL', 'FLGT', 'FLNC', 'FLNT', 'FLXS', 'FONR', 'FOSL', 'FRHC', 'FRST', 'FSBW', 'FSEA', 'FSLR', 'FTCI', 'FTRE', 'FULC', 'GABC', 'GALT', 'GCBC', 'GCMG', 'GCTS', 'GDOT', 'GECC', 'GENC', 'GENI', 'GENK', 'GEOS', 'GERN', 'GEVO', 'GHRS', 'GILD', 'GLPG', 'GLPI', 'GLRE', 'GMAB', 'GNOM', 'GNSS', 'GOSS', 'GPAC', 'GPMT', 'GRAB', 'GRAL', 'GREE', 'GRFS', 'GRPN', 'GRWG', 'GSBC', 'GTIM', 'GTLB', 'GURE', 'GWRS', 'HALO', 'HCAT', 'HCKT', 'HCWB', 'HCXY', 'HEPS', 'HFFG', 'HIHO', 'HIMS', 'HLIO', 'HLNE', 'HNNA', 'HNRG', 'HOFT', 'HOMB', 'HOMZ', 'HOOK', 'HOTH', 'HOWL', 'HRMY', 'HROW', 'HSDT', 'HTOO', 'HUMA', 'HURN', 'IART', 'IBEX', 'IBRX', 'ICCC', 'ICFI', 'ICHR', 'ICMB', 'IDAI', 'IDCC', 'IDEV', 'IDYA', 'IIIV', 'IINN', 'IIPR', 'ILMN', 'IMAQ', 'IMCR', 'IMCV', 'IMDX', 'IMMP', 'IMNN', 'IMTX', 'IMUX', 'IMVT', 'IMXI', 'INAB', 'INBK', 'INBX', 'INDB', 'INFU', 'INMD', 'INOD', 'INSE', 'INTA', 'INTJ', 'INTT', 'INTU', 'INTZ', 'INVA', 'INVE', 'INVX', 'IOSP', 'IOVA', 'IPDN', 'IPIX', 'IPWR', 'IRDM', 'IRMD', 'ISPC', 'ISPR', 'ISRG', 'ISSC', 'ITRN', 'ITRI', 'IVDA', 'IVVD', 'JAKK', 'JANX', 'JBSS', 'JELD', 'JFIN', 'JMSB', 'JOBY', 'JOUT', 'JPC', 'JRSH', 'JSPR', 'JUNS', 'KALA', 'KALU', 'KFRC', 'KIDS', 'KINS', 'KLIC', 'KLXE', 'KMDA', 'KMPB', 'KNSA', 'KNSL', 'KOSS', 'KPLT', 'KRKR', 'KRMD', 'KRNT', 'KROS', 'KSCP', 'KTEL', 'KTTA', 'KURA', 'LASE', 'LASR', 'LBRT', 'LCII', 'LCNB', 'LCUT', 'LEGN', 'LGIH', 'LGMK', 'LGND', 'LKFN', 'LMB', 'LNN', 'LNTH', 'LNZA', 'LOCO', 'LOGC', 'LOPE', 'LOVE', 'LPRO', 'LPX', 'LQDT', 'LRCX', 'LSAK', 'LSTR', 'LTRX', 'LUNA', 'LVWR', 'LWAY', 'LXP', 'LYEL', 'LYFT', 'LYTS', 'MAQC', 'MASI', 'MATV', 'MATW', 'MAXN', 'MBIN', 'MBWM', 'MCBS', 'MCFT', 'MCRB', 'MCVT', 'MDGL', 'MDXG', 'MEIP', 'MGAM', 'MGNX', 'MGTX', 'MIND', 'MINN', 'MIRM', 'MKSI', 'MKTW', 'MLCO', 'MMSI', 'MNR', 'MNST', 'MORN', 'MPAA', 'MPLX', 'MPWR', 'MRCY', 'MRTN', 'MSTR', 'MTG', 'MTN', 'MTRX', 'MUR', 'MVBF', 'MYFW', 'MYPS', 'MYRG', 'NAUT', 'NBTB', 'NCMI', 'NCSM', 'NDLS', 'NFBK', 'NGS', 'NKTR', 'NMFC', 'NMHI', 'NMIH', 'NNI', 'NNOX', 'NOMD', 'NOVT', 'NPO', 'NPWR', 'NRDS', 'NRIM', 'NRIX', 'NRSN', 'NSA', 'NSP', 'NTST', 'NVAX', 'NVCR', 'NVDS', 'NVNO', 'NWPX', 'NXG', 'OABI', 'OBIO', 'OCFC', 'OCGN', 'OCIO', 'OFIX', 'OGCP', 'OGN', 'OHI', 'OIS', 'OKLO', 'OLED', 'OMAB', 'OMCL', 'OMF', 'OMQS', 'ONEW', 'ONL', 'ONMD', 'ONON', 'ONPH', 'ORCL', 'ORGO', 'ORLA', 'OSIS', 'OSUR', 'OTLK', 'OVID', 'OXLC', 'OXM', 'PAHC', 'PANL', 'PARR', 'PASG', 'PAVS', 'PAYO', 'PCRX', 'PCSA', 'PDFS', 'PDYN', 'PEBO', 'PESI', 'PFIS', 'PGNY', 'PHIO', 'PHVS', 'PIII', 'PINC', 'PIPR', 'PKBK', 'PKE', 'PKOH', 'PLAB', 'PLCE', 'PLPC', 'PLRX', 'PLSE', 'PLUR', 'PMT', 'PODD', 'POOL', 'POWI', 'POWL', 'PPSI', 'PRAA', 'PRIM', 'PRLD', 'PRME', 'PRPH', 'PRQR', 'PRST', 'PRT', 'PSFE', 'PSTL', 'PTCT', 'PTIX', 'PTLO', 'PUMP', 'PYPD', 'QDEL', 'QLYS', 'QNST', 'QRHC', 'QUAD', 'QUBT', 'RAIL', 'RAMP', 'RAVE', 'RCKY', 'RCUS', 'RDVT', 'RELY', 'REZI', 'REXR', 'RGNX', 'RICK', 'RILY', 'RIVN', 'RKT', 'RMBI', 'RMCF', 'RMNI', 'RMR', 'ROCK', 'ROG', 'RPRX', 'RRC', 'RRBI', 'RRGB', 'RRR', 'RRTS', 'RSSS', 'RUN', 'RUSHA', 'RUSHB', 'RXRX', 'RVSB', 'SBCF', 'SBFG', 'SBGI', 'SBSI', 'SCL', 'SCSC', 'SDOT', 'SEER', 'SFM', 'SFNC', 'SFST', 'SGHT', 'SHBI', 'SHLS', 'SHOO', 'SIG', 'SITM', 'SKYW', 'SLG', 'SLVM', 'SM', 'SMTC', 'SNDR', 'SONX', 'SPFI', 'SPSC', 'SPWH', 'SRI', 'SRPT', 'SSBI', 'SST', 'STAA', 'STBA', 'STEP', 'STGW', 'STNG', 'STOK', 'STRA', 'STRR', 'STRS', 'SUPN', 'SUPX', 'SWBI', 'SWIM', 'SYBT', 'SYRE', 'TALO', 'TBPH', 'TCBK', 'TCRX', 'TDI', 'TELA', 'TILE', 'TIPT', 'TLYS', 'TMHC', 'TOWN', 'TPB', 'TPC', 'TPVG', 'TRMK', 'TRNO', 'TRS', 'TRTX', 'TTGT', 'TUSK', 'TVC', 'TZOO', 'UE', 'UEC', 'UEIC', 'UFI', 'UGI', 'UHT', 'ULBI', 'ULCC', 'UMBF', 'UNF', 'UNIT', 'UNTY', 'UPBD', 'URBN', 'URNM', 'USFD', 'USLM', 'UTMD', 'UTZ', 'UVSP', 'VCNX', 'VCYT', 'VECO', 'VEON', 'VERA', 'VERX', 'VIRT', 'VITL', 'VLGEA', 'VNET', 'VNRX', 'VRTS', 'VRE', 'VSAT', 'VSEC', 'VTOL', 'VVOS', 'WABC', 'WBHC', 'WCLD', 'WAFD', 'WASH', 'WERN', 'WEYS', 'WGO', 'WINA', 'WLFC', 'WOLF', 'WOR', 'WORX', 'WRLD', 'WS', 'WSBC', 'WSBF', 'WSFS', 'WSR', 'WTFC', 'WTTR', 'WULF', 'WWR', 'XNCR', 'YELP', 'YORW', 'ZUMZ']

USA_SMALLCAP_SP600 = ['ABCB', 'ACNB', 'BSVN', 'BUSE', 'CBAN', 'CCBG', 'CCNE', 'CFFI', 'CHCO', 'CIVB', 'CNOB', 'CVBF', 'DCOM', 'EFSC', 'FBNC', 'FBRT', 'FFBC', 'FISI', 'FMBH', 'FMNB', 'FRME', 'FRST', 'FULT', 'FUNC', 'GSBC', 'HCSG', 'HCI', 'HFFG', 'HFWA', 'IBCP', 'IBOC', 'ITIC', 'ITRN', 'JRVR', 'LCNB', 'LKFN', 'LTC', 'MCY', 'MFIN', 'MYFW', 'NBTB', 'NFBK', 'PEBO', 'PFIS', 'PIPR', 'PKBK', 'PRAA', 'PSTL', 'RMR', 'SBCF', 'SBSI', 'SFST', 'SHBI', 'SPFI', 'STBA', 'SYBT', 'TCBK', 'TRMK', 'UVSP', 'WABC', 'WAFD', 'WASH', 'WSBC', 'WSBF', 'WSR', 'AX', 'BHR', 'GOOD', 'HQI', 'HTH', 'JOE', 'LMB', 'TPVG', 'TRTX', 'UE', 'UHT', 'VRE', 'WS', 'EPRT', 'STAG', 'SKT', 'SITM', 'ABG', 'ACVA', 'AEO', 'ANF', 'ASO', 'BKE', 'BJRI', 'CATO', 'CRMT', 'ETD', 'FORR', 'IMKTA', 'JACK', 'JJSF', 'JOUT', 'LOCO', 'LOVE', 'NDLS', 'OXM', 'PLCE', 'RCKY', 'RICK', 'RRGB', 'RUSHA', 'RUSHB', 'SHOO', 'TLYS', 'TOWN', 'TZOO', 'VLGEA', 'WRLD', 'WEYS', 'WGO', 'ZUMZ', 'GOLF', 'CAKE', 'CORT', 'LOPE', 'PRPH', 'SPWH', 'BGS', 'CALM', 'CARG', 'CASH', 'CENT', 'CENTA', 'CVCO', 'JBSS', 'MGPI', 'PAHC', 'SCL', 'SFM', 'UTZ', 'APEI', 'AIN', 'ALTG', 'AMSC', 'AMWD', 'ANDE', 'APOG', 'ARCB', 'ARCO', 'AROC', 'ASTE', 'ATNI', 'ATRO', 'AWI', 'AXTI', 'BLBD', 'BRC', 'CLW', 'CMCO', 'CRC', 'CSTE', 'CTS', 'DLX', 'DNOW', 'DY', 'EPAC', 'EXPO', 'FRD', 'FSS', 'GEF', 'GFF', 'GHM', 'GVA', 'HWKN', 'LASR', 'LMB', 'LNN', 'MATW', 'MG', 'MPAA', 'MRTN', 'MTRX', 'NPO', 'POWL', 'PRIM', 'PUMP', 'RCKY', 'ROCK', 'ROG', 'SCL', 'SCSC', 'SKYW', 'SNDR', 'SRI', 'TUSK', 'UFI', 'VSEC', 'WERN', 'WOR', 'WLFC', 'WTTR', 'BLX', 'HARL', 'KFY', 'KFRC', 'LCII', 'LYTS', 'NNI', 'TPC', 'UEIC', 'UNF', 'UNIT', 'CWK', 'DFH', 'LGIH', 'TMHC', 'ACLS', 'AEIS', 'AMKR', 'AMPH', 'APPF', 'BLKB', 'CEVA', 'CLFD', 'COHU', 'CRSR', 'DGII', 'FORM', 'IESC', 'IOSP', 'LCUT', 'LTRX', 'NABL', 'NOVT', 'PDFS', 'PGNY', 'PINC', 'QNST', 'RDVT', 'RELY', 'SMTC', 'SPSC', 'STAA', 'TTGT', 'VERX', 'VIRT', 'VRTS', 'XNCR', 'AMBA', 'ANIK', 'APAM', 'LNTH', 'LUNA', 'MINN', 'OSBC', 'PAYO', 'ACVA', 'ADMA', 'ADNT', 'ADUS', 'AHCO', 'ALKS', 'ALRM', 'AMRX', 'ARDX', 'ARWR', 'ASTH', 'ATEX', 'AVNS', 'BCPC', 'CFFI', 'CHRS', 'CRIS', 'CVBF', 'ECPG', 'EIG', 'ENSG', 'ESCA', 'FBRT', 'FCEL', 'HRMY', 'HROW', 'ICFI', 'INFU', 'IPAR', 'IRMD', 'IRWD', 'KIDS', 'KNSA', 'LNTH', 'MDGL', 'MERC', 'METC', 'MIRM', 'MMSI', 'MYRG', 'NCMI', 'NRIM', 'OMCL', 'OSIS', 'PAHC', 'PESI', 'PGNY', 'RCUS', 'RGNX', 'SUPN', 'TCRX', 'TELA', 'TILE', 'VCYT', 'VTOL', 'AVNT', 'AVNW', 'CORT', 'IRTC', 'BTU', 'CRC', 'CRK', 'CVI', 'DFH', 'GPRE', 'KOS', 'KRO', 'METC', 'NOG', 'NOMD', 'SRI', 'STNG', 'TALO', 'TPC', 'UEC', 'VTOL', 'REX', 'AMCX', 'BXC', 'CSL', 'CWT', 'GEF', 'INFU', 'KRO', 'QUBT', 'SLVM', 'UNF', 'AWR', 'CABO', 'CXW', 'HLX', 'HOPE', 'LTC', 'NWE', 'OFED', 'OIS', 'QUAD', 'TRNO', 'TRS', 'UHT', 'USLM', 'UTMD', 'WGO', 'WINA', 'YORW', 'NX', 'ABCB', 'ACNB', 'ALLO', 'ALTO', 'AOSL', 'ARCB', 'ARHS', 'ARIS', 'ARLO', 'ASO', 'ASPS', 'ATEN', 'BELFB', 'BKSC', 'BLBD', 'BOC', 'BTU', 'BWFG', 'CIVB', 'CLNE', 'CNMD', 'CPSS', 'CPS', 'CXW', 'DSP', 'EIX', 'ENSG', 'EVTC', 'FBNC', 'GCMG', 'GKOS', 'GOGO', 'GRNT', 'HAIN', 'HALL', 'HALO', 'HCAT', 'HIFS', 'HIT', 'IBCP', 'IMKTA', 'INTA', 'INTL', 'ITRN', 'JELD', 'JPC', 'JRSH', 'KIDS', 'KMT', 'KNSL', 'KRNT', 'LCNB', 'LCUT', 'LGIH', 'LKFN', 'LNN', 'LOCO', 'LOVE', 'LUNA', 'MATW', 'MBIN', 'MBWM', 'MFIN', 'MG', 'MINN', 'MPAA', 'MRTN', 'MTRX', 'MYFW', 'MYRG', 'NABL', 'NBTB', 'NCMI', 'NDLS', 'NFBK', 'NGS', 'NNI', 'NRIM', 'NWE', 'OBT', 'OFED', 'OFIX', 'OIS', 'OXM', 'PAYO', 'PDFS', 'PEBO', 'PESI', 'PFIS', 'PIPR', 'PKE', 'PLCE', 'POWL', 'PRAA', 'PSTL', 'PUMP', 'RCKY', 'RCUS', 'RDVT', 'RELY', 'REX', 'RGNX', 'RICK', 'RILY', 'ROCK', 'ROG', 'SBCF', 'SBSI', 'SFST', 'SHBI', 'SHLS', 'SHOO', 'SITM', 'SKYW', 'SMTC', 'SNDR', 'SPFI', 'SPSC', 'SPWH', 'SRI', 'STBA', 'STNG', 'STRA', 'STRR', 'SUPN', 'SWBI', 'SYBT', 'TALO', 'TCBK', 'TCRX', 'TELA', 'TILE', 'TLYS', 'TMHC', 'TOWN', 'TPB', 'TPVG', 'TRMK', 'TRNO', 'TRS', 'TRTX', 'TTGT', 'TZOO', 'UE', 'UEC', 'UEIC', 'UFI', 'UHT', 'UNF', 'UNIT', 'UNTY', 'UPBD', 'USLM', 'UTMD', 'UTZ', 'UVSP', 'VCYT', 'VERX', 'VIRT', 'VLGEA', 'VRTS', 'VSEC', 'VTOL', 'WABC', 'WAFD', 'WASH', 'WERN', 'WEYS', 'WGO', 'WLFC', 'WOR', 'WRLD', 'WSBC', 'WSBF', 'WSR', 'WTTR', 'XNCR', 'YORW', 'ZUMZ']

UK_FTSE100 = ['AAL.L', 'ABF.L', 'ADM.L', 'ANTO.L', 'AUTO.L', 'AV.L', 'AZN.L', 'BA.L', 'BARC.L', 'BATS.L', 'BNZL.L', 'BP.L', 'BRBY.L', 'BT-A.L', 'CCH.L', 'CNA.L', 'CPG.L', 'CRDA.L', 'DCC.L', 'DGE.L', 'EXPN.L', 'FERG.L', 'FRES.L', 'GLEN.L', 'GSK.L', 'HLN.L', 'HLMA.L', 'HIK.L', 'HSBA.L', 'IAG.L', 'IHG.L', 'IMB.L', 'INF.L', 'ITRK.L', 'JD.L', 'KGF.L', 'LAND.L', 'LGEN.L', 'LLOY.L', 'LSEG.L', 'MKS.L', 'MNDI.L', 'MNG.L', 'NG.L', 'NWG.L', 'NXT.L', 'OCDO.L', 'PSON.L', 'PSN.L', 'PRU.L', 'PSH.L', 'PTEC.L', 'REL.L', 'RIO.L', 'RKT.L', 'RMV.L', 'RR.L', 'RTO.L', 'SBRY.L', 'SDR.L', 'SGRO.L', 'SHEL.L', 'SMT.L', 'SMIN.L', 'SPX.L', 'SSE.L', 'STAN.L', 'STJ.L', 'SVT.L', 'TSCO.L', 'TW.L', 'ULVR.L', 'UTG.L', 'UU.L', 'VOD.L', 'WEIR.L', 'WPP.L', 'WTB.L']

UK_FTSE250 = ['OSB.L', 'LRE.L', 'SBRE.L', 'IGG.L', 'PAG.L', 'MONY.L', 'PRU.L', 'BLND.L', 'LMP.L', 'WKP.L', 'SAFE.L', 'TRY.L', 'CREI.L', 'BBOX.L', 'PHP.L', 'SUPR.L', 'MGNS.L', 'HILS.L', 'IMI.L', 'BOY.L', 'SNR.L', 'VCT.L', 'VSVS.L', 'KLR.L', 'HTG.L', 'WEIR.L', 'SPX.L', 'MGAM.L', 'XPP.L', 'QQ.L', 'DRX.L', 'MSLH.L', 'SHI.L', 'CLX.L', 'GRG.L', 'DNLM.L', 'DFS.L', 'HFD.L', 'WOSG.L', 'MAB.L', 'BOWL.L', 'JDW.L', 'TPK.L', 'MER.L', 'PFD.L', 'BOOK.L', 'THG.L', 'GFTU.L', 'RSW.L', 'HAS.L', 'CCC.L', 'NCC.L', 'POLR.L', 'EMH.L', 'SPXG.L', 'RWS.L', 'ELM.L', 'SYNT.L', 'ATG.L', 'AUTO.L', 'FUTR.L', 'ITV.L', 'IPO.L', 'RMV.L', 'AO.L', 'CMCX.L', 'HGT.L', 'PAGE.L', 'TLW.L', 'ENQ.L', 'KMR.L', 'FXPO.L', 'PAF.L', 'CNE.L', 'EMG.L', 'ENOG.L', 'SRES.L', 'BBOX.L', 'SGRO.L', 'AEWU.L', 'PCTN.L', 'NRR.L', 'WINK.L', 'THRL.L', 'FGP.L', 'GNC.L', 'EXPN.L', 'TBCG.L', 'BGEO.L', 'OSB.L', 'SQZ.L', 'VANL.L', 'CLIG.L', 'RNK.L', 'SVS.L', 'ESNT.L', 'SMIN.L', 'PAY.L', 'TTG.L', 'ASPL.L', 'SDR.L']

GERMANY_DAX = [ 'ADS.DE', 'AIR.DE', 'ALV.DE', 'BAS.DE', 'BAYN.DE', 'BEI.DE', 'BMW.DE', 'BNR.DE', 'CON.DE', 'DB1.DE', 'DBK.DE', 'DHL.DE', 'DTE.DE', 'DWNI.DE', 'EOAN.DE', 'FME.DE', 'FRE.DE', 'HEI.DE', 'HEN3.DE', 'IFX.DE', 'LIN.DE', 'MBG.DE', 'MRK.DE', 'MTX.DE', 'MUV2.DE', 'P911.DE', 'PAH3.DE', 'RWE.DE', 'SAP.DE', 'SDF.DE', 'SIE.DE', 'SY1.DE', 'VOW3.DE', 'VNA.DE', 'ZAL.DE']

GERMANY_MDAX = ['AIXA.DE', 'BC8.DE', 'BOSS.DE', 'BYW6.DE', 'DEQ.DE', 'DMP.DE', 'DWS.DE', 'ENR.DE', 'EVK.DE', 'FNTN.DE', 'FPE3.DE', 'GBF.DE', 'HAG.DE', 'HDD.DE', 'HNR1.DE', 'HOT.DE', 'JEN.DE', 'KGX.DE', 'LEG.DE', 'LXS.DE', 'NOEJ.DE', 'PUM.DE', 'PSM.DE', 'QIA.DE', 'RAA.DE', 'RSL2.DE', 'S92.DE', 'TKA.DE', 'TLX.DE', 'TUI1.DE', 'UTDI.DE', 'VBK.DE', 'WAF.DE', 'WCH.DE', 'AAD.DE', 'AFX.DE', 'AT1.DE', 'BFSA.DE', 'CAP.DE', 'CLIQ.DE', 'DRW3.DE', 'DWNI.DE', 'EBK.DE', 'EDL.DE', 'EVD.DE', 'EVT.DE', 'FIE.DE', 'GFT.DE', 'HAW.DE', 'HBH.DE', 'INH.DE', 'NDX1.DE', 'NEM.DE', 'OHB.DE', 'PBB.DE', 'SGL.DE', 'SIS.DE', 'SKB.DE', 'STO3.DE', 'TTK.DE', 'VIB3.DE', 'VOS.DE', 'WAT.DE', 'ZIL2.DE']

FRANCE_CAC40 = ['AC.PA', 'AIR.PA', 'ALO.PA', 'ATO.PA', 'BN.PA', 'BNP.PA', 'CA.PA', 'CAP.PA', 'CS.PA', 'DG.PA', 'DSY.PA', 'EL.PA', 'EN.PA', 'ERF.PA', 'FR.PA', 'GLE.PA', 'HO.PA', 'KER.PA', 'LR.PA', 'MC.PA', 'ML.PA', 'OR.PA', 'ORA.PA', 'PUB.PA', 'RI.PA', 'RMS.PA', 'SAF.PA', 'SAN.PA', 'SGO.PA', 'STLAP.PA', 'STMPA.PA', 'SU.PA', 'TEP.PA', 'TTE.PA', 'URW.PA', 'VIE.PA', 'VIV.PA']

FRANCE_MIDCAP = ['AF.PA', 'AMUN.PA', 'BB.PA', 'COFA.PA', 'DBV.PA', 'EDEN.PA', 'FNAC.PA', 'GET.PA', 'GTT.PA', 'ICAD.PA', 'IPH.PA', 'LNA.PA', 'MAU.PA', 'MRN.PA', 'NEX.PA', 'NK.PA', 'QDT.PA', 'RCO.PA', 'RNO.PA', 'SESG.PA', 'SMCP.PA', 'SPIE.PA', 'TFF.PA', 'UBI.PA', 'VAL.PA', 'VCT.PA', 'VIE.PA', 'WORLD.PA', 'WLN.PA', 'ABCA.PA', 'ATE.PA', 'ATO.PA', 'AUB.PA', 'AURE.PA', 'BEN.PA', 'BOL.PA', 'BUR.PA', 'BVI.PA', 'CLARI.PA', 'COUR.PA', 'ERA.PA']

ITALY_MIB = ['A2A.MI', 'AZM.MI', 'BAMI.MI', 'BGN.MI', 'BMED.MI', 'BPE.MI', 'BZU.MI', 'CPR.MI', 'DIA.MI', 'ENI.MI', 'ERG.MI', 'ENEL.MI', 'FBK.MI', 'G.MI', 'HER.MI', 'INW.MI', 'IP.MI', 'ISP.MI', 'LDO.MI', 'MB.MI', 'MONC.MI', 'PIRC.MI', 'PST.MI', 'PRY.MI', 'RACE.MI', 'REC.MI', 'SPM.MI', 'SRG.MI', 'TEN.MI', 'TIT.MI', 'TRN.MI', 'UCG.MI', 'UNI.MI']

SPAIN_IBEX = ['ACX.MC', 'ACS.MC', 'AMS.MC', 'ANA.MC', 'BBVA.MC', 'BKT.MC', 'CAF.MC', 'CABK.MC', 'CLNX.MC', 'COL.MC', 'ELE.MC', 'ENG.MC', 'FDR.MC', 'FER.MC', 'GRF.MC', 'IAG.MC', 'IBE.MC', 'IDR.MC', 'ITX.MC', 'LOG.MC', 'MAP.MC', 'MEL.MC', 'MRL.MC', 'NTGY.MC', 'PHM.MC', 'RED.MC', 'REP.MC', 'ROVI.MC', 'SAB.MC', 'SAN.MC', 'SCYR.MC', 'SLR.MC', 'TEF.MC']

SWISS_SMI = ['ABBN.SW', 'CFR.SW', 'GEBN.SW', 'GIVN.SW', 'HOLN.SW', 'LONN.SW', 'NESN.SW', 'NOVN.SW', 'PGHN.SW', 'SIKA.SW', 'SLHN.SW', 'SREN.SW', 'UBSG.SW', 'UHRN.SW', 'ZURN.SW', 'SCMN.SW', 'SOON.SW']

NETHERLANDS_AEX = ['ASML.AS', 'INGA.AS', 'HEIA.AS', 'PHIA.AS', 'ABN.AS', 'PRX.AS', 'ADYEN.AS', 'AKZA.AS', 'NN.AS', 'WKL.AS', 'RAND.AS', 'UMG.AS', 'LIGHT.AS']

SWEDEN_OMXS = ['ERIC-B.ST', 'HM-B.ST', 'VOLV-B.ST', 'SAND.ST', 'SWED-A.ST', 'SHB-A.ST', 'SEB-A.ST', 'ATCO-A.ST', 'ATCO-B.ST', 'ASSA-B.ST', 'EVO.ST', 'INVE-B.ST', 'ALFA.ST', 'SKF-B.ST', 'ELUX-B.ST', 'NDA-SE.ST', 'HEXA-B.ST', 'SECU-B.ST', 'TEL2-B.ST', 'TELIA.ST', 'BOL.ST', 'SSAB-A.ST', 'SCA-B.ST', 'GETI-B.ST']

NORWAY_OBX = ['EQNR.OL', 'DNB.OL', 'TEL.OL', 'ORK.OL', 'MOWI.OL', 'YAR.OL', 'AKSO.OL', 'SUBC.OL', 'SALM.OL', 'NHY.OL', 'SCATC.OL', 'AUSS.OL', 'BAKKA.OL', 'NEL.OL', 'AKER.OL', 'TGS.OL', 'KOG.OL', 'STB.OL']

DENMARK_OMXC = ['NOVO-B.CO', 'MAERSK-B.CO', 'DSV.CO', 'CARL-B.CO', 'ORSTED.CO', 'VWS.CO', 'RBREW.CO', 'PNDORA.CO', 'GN.CO', 'AMBU-B.CO', 'DEMANT.CO', 'TRYG.CO']

FINLAND_OMXH = ['NOKIA.HE', 'NESTE.HE', 'FORTUM.HE', 'SAMPO.HE', 'UPM.HE', 'ELISA.HE', 'STERV.HE', 'KEMIRA.HE', 'ORNBV.HE']

BELGIUM_BEL20 = ['ABI.BR', 'ACKB.BR', 'AGS.BR', 'ARGX.BR', 'COLR.BR', 'ECONB.BR', 'GBLB.BR', 'KBC.BR', 'MELE.BR', 'ONTEX.BR', 'PROX.BR', 'SOLB.BR', 'UCB.BR', 'UMI.BR', 'WDP.BR', 'COFB.BR', 'LOTB.BR', 'BPOST.BR', 'VGP.BR']

AUSTRIA_ATX = [ 'AT1.VI', 'BKS.VI', 'BNB.VI', 'CAI.VI', 'DO.VI', 'EBS.VI', 'EVN.VI', 'FLU.VI', 'IIA.VI', 'IMMO.VI', 'OMV.VI', 'OTE.VI', 'POST.VI', 'RBI.VI', 'SBO.VI', 'SEM.VI', 'VER.VI', 'VIG.VI', 'VOE.VI', 'WIE.VI']

PORTUGAL_PSI = ['ALTR.LS', 'BCP.LS', 'COR.LS', 'CTT.LS', 'EDP.LS', 'EDPR.LS', 'EGL.LS', 'GALP.LS', 'MCP.LS', 'NOS.LS', 'NVG.LS', 'PHP.LS', 'SON.LS']

JAPAN_NIKKEI = ['7203.T', '6758.T', '9984.T', '6861.T', '9433.T', '8306.T', '8316.T', '4063.T', '6954.T', '6902.T', '4502.T', '4503.T', '6098.T', '8031.T', '8035.T', '7974.T', '4568.T', '2914.T', '4452.T', '4911.T', '8001.T', '8058.T', '3382.T', '8053.T', '5108.T', '9020.T', '9022.T', '9101.T', '5401.T', '5713.T']

JAPAN_TOPIX_EXT = ['7267.T', '7269.T', '7201.T', '7270.T', '7272.T', '7211.T', '7261.T', '7011.T', '7012.T', '7013.T', '6752.T', '6501.T', '6702.T', '6723.T', '6762.T', '6971.T', '6506.T', '6367.T', '6503.T', '6273.T', '6645.T', '6841.T', '6988.T', '6920.T', '7735.T', '7741.T', '7733.T', '7751.T', '6770.T', '6857.T', '6479.T', '4901.T', '6301.T', '6326.T', '5802.T', '5801.T', '6471.T', '7309.T', '6302.T', '7752.T', '4704.T', '9613.T', '3659.T', '4307.T', '2413.T', '4755.T', '9983.T', '8411.T', '8309.T', '8725.T', '8750.T', '8766.T', '8795.T', '8591.T', '8697.T', '8601.T', '8604.T', '4519.T', '4523.T', '4151.T', '4543.T', '4506.T', '4578.T', '4507.T', '4902.T', '4188.T', '3407.T', '4005.T', '4021.T', '4183.T', '5020.T', '5019.T', '3402.T', '4042.T', '4612.T', '5233.T', '4204.T', '3105.T', '4061.T', '5406.T', '2502.T', '2503.T', '2587.T', '2897.T', '2269.T', '2801.T', '2282.T', '2871.T', '7936.T', '7832.T', '4661.T', '8267.T', '9843.T', '3086.T', '3099.T', '8233.T', '9735.T', '8252.T', '1925.T', '1928.T', '8802.T', '8830.T', '8801.T', '3289.T', '9432.T', '9434.T', '9202.T', '9201.T', '9064.T', '9005.T', '9007.T', '9008.T', '9104.T', '8015.T', '8002.T', '9531.T', '9532.T', '9501.T', '9502.T', '9503.T', '5411.T', '5706.T', '3941.T', '3861.T', '3101.T']

HK_HANGSENG = ['0700.HK', '9988.HK', '0941.HK', '1299.HK', '0939.HK', '2318.HK', '0388.HK', '1398.HK', '3988.HK', '0005.HK', '0001.HK', '0016.HK', '0003.HK', '0688.HK', '0883.HK', '0002.HK', '0017.HK', '2382.HK', '1113.HK']

KOREA_KOSPI = ['005930.KS', '000660.KS', '373220.KS', '207940.KS', '005380.KS', '000270.KS', '051910.KS', '068270.KS', '028260.KS', '105560.KS', '055550.KS', '086790.KS', '316140.KS', '032830.KS', '138040.KS', '024110.KS', '006800.KS', '039490.KS', '071050.KS', '003550.KS', '017670.KS', '030200.KS', '066570.KS', '035420.KS', '035720.KS', '259960.KS', '042700.KS', '032640.KS', '096770.KS', '011070.KS', '012330.KS', '086280.KS', '000830.KS', '004020.KS', '000720.KS', '034730.KS', '009150.KS', '018260.KS', '161390.KS', '329180.KS', '010950.KS', '011170.KS', '096530.KS', '011790.KS', '010140.KS', '006400.KS', '003490.KS', '267260.KS', '180640.KS', '011200.KS', '326030.KS', '128940.KS', '170900.KS', '302440.KS', '263750.KS', '145020.KS', '036570.KS', '293490.KS', '214150.KS', '108670.KS', '004370.KS', '097950.KS', '271560.KS', '000100.KS', '282330.KS', '139480.KS', '005070.KS', '011780.KS', '001800.KS', '009830.KS', '005490.KS', '004490.KS', '010130.KS', '001440.KS', '002380.KS', '042660.KS', '047050.KS', '064350.KS', '015760.KS', '036460.KS']

BRAZIL_IBOVESPA = ['PETR4.SA', 'PETR3.SA', 'PRIO3.SA', 'CSAN3.SA', 'UGPA3.SA', 'RECV3.SA', 'RRRP3.SA', 'VBBR3.SA', 'EGIE3.SA', 'CMIG4.SA', 'CPFE3.SA', 'ELET3.SA', 'ELET6.SA', 'SBSP3.SA', 'CPLE6.SA', 'VALE3.SA', 'GGBR4.SA', 'USIM5.SA', 'CSNA3.SA', 'BRAP4.SA', 'KLBN11.SA', 'SUZB3.SA', 'DXCO3.SA', 'SEER3.SA', 'ITUB4.SA', 'BBDC4.SA', 'BBDC3.SA', 'BBAS3.SA', 'B3SA3.SA', 'SANB11.SA', 'BPAC11.SA', 'IRBR3.SA', 'SULA11.SA', 'PSSA3.SA', 'ABEV3.SA', 'LREN3.SA', 'MGLU3.SA', 'ASAI3.SA', 'PCAR3.SA', 'CRFB3.SA', 'ALPA4.SA', 'SOMA3.SA', 'ARZZ3.SA', 'GMAT3.SA', 'HYPE3.SA', 'RADL3.SA', 'RDOR3.SA', 'HAPV3.SA', 'FLRY3.SA', 'QUAL3.SA', 'TOTS3.SA', 'VIVT3.SA', 'LWSA3.SA', 'INTB3.SA', 'NTCO3.SA', 'WEGE3.SA', 'RAIL3.SA', 'EMBR3.SA', 'JBSS3.SA', 'BRFS3.SA', 'MRFG3.SA', 'BEEF3.SA', 'SMTO3.SA', 'CYRE3.SA', 'EZTC3.SA', 'MRVE3.SA', 'MULT3.SA', 'IGTI11.SA', 'RENT3.SA', 'MOVI3.SA', 'PETZ3.SA', 'GOLL4.SA', 'AZUL4.SA']

INDIA_NIFTY = ['RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS', 'WIPRO.NS', 'HCLTECH.NS', 'TECHM.NS', 'MPHASIS.NS', 'PERSISTENT.NS', 'COFORGE.NS', 'KPITTECH.NS', 'TATAELXSI.NS', 'OFSS.NS', 'NAUKRI.NS', 'DIXON.NS', 'CYIENT.NS', 'BHARTIARTL.NS', 'TATACOMM.NS', 'AXISBANK.NS', 'KOTAKBANK.NS', 'BAJFINANCE.NS', 'SBIN.NS', 'INDUSINDBK.NS', 'PNB.NS', 'CANBK.NS', 'BANKBARODA.NS', 'BAJAJFINSV.NS', 'HDFCAMC.NS', 'CHOLAFIN.NS', 'MUTHOOTFIN.NS', 'SBICARD.NS', 'LICHSGFIN.NS', 'PNBHOUSING.NS', 'MANAPPURAM.NS', 'SUNDARMFIN.NS', 'BAJAJHLDNG.NS', 'CRISIL.NS', 'LTF.NS', 'HDFCLIFE.NS', 'SBILIFE.NS', 'ICICIPRULI.NS', 'MFSL.NS', 'SUNPHARMA.NS', 'DRREDDY.NS', 'CIPLA.NS', 'DIVISLAB.NS', 'TORNTPHARM.NS', 'LUPIN.NS', 'AUROPHARMA.NS', 'ALKEM.NS', 'ZYDUSLIFE.NS', 'MANKIND.NS', 'IPCALAB.NS', 'BIOCON.NS', 'APOLLOHOSP.NS', 'MAXHEALTH.NS', 'FORTIS.NS', 'LALPATHLAB.NS', 'METROPOLIS.NS', 'M&M.NS', 'BAJAJ-AUTO.NS', 'HEROMOTOCO.NS', 'EICHERMOT.NS', 'ESCORTS.NS', 'APOLLOTYRE.NS', 'MRF.NS', 'BALKRISIND.NS', 'CEATLTD.NS', 'MOTHERSON.NS', 'TIINDIA.NS', 'ENDURANCE.NS', 'SCHAEFFLER.NS', 'TIMKEN.NS', 'LT.NS', 'LTTS.NS', 'ADANIENT.NS', 'ADANIPORTS.NS', 'ADANIGREEN.NS', 'ADANIPOWER.NS', 'TATAPOWER.NS', 'TATACHEM.NS', 'TATACONSUM.NS', 'TATASTEEL.NS', 'HINDALCO.NS', 'JSWSTEEL.NS', 'VEDL.NS', 'COALINDIA.NS', 'ONGC.NS', 'NMDC.NS', 'ULTRACEMCO.NS', 'SHREECEM.NS', 'AMBUJACEM.NS', 'ACC.NS', 'DALBHARAT.NS', 'JKCEMENT.NS', 'HINDUNILVR.NS', 'ITC.NS', 'NESTLEIND.NS', 'BRITANNIA.NS', 'DABUR.NS', 'MARICO.NS', 'COLPAL.NS', 'GODREJCP.NS', 'TRENT.NS', 'TITAN.NS', 'ASIANPAINT.NS', 'PIDILITIND.NS', 'BERGEPAINT.NS', 'MARUTI.NS', 'JUBLFOOD.NS', 'PVRINOX.NS', 'INDHOTEL.NS', 'EIHOTEL.NS', 'DEEPAKNTR.NS', 'SRF.NS', 'PIIND.NS', 'AARTIIND.NS', 'NAVINFLUOR.NS', 'ATUL.NS', 'NTPC.NS', 'POWERGRID.NS', 'BPCL.NS', 'IOC.NS', 'GAIL.NS', 'PETRONET.NS', 'IGL.NS', 'MGL.NS', 'NHPC.NS', 'IREDA.NS', 'SJVN.NS', 'PFC.NS', 'RECLTD.NS', 'JSWENERGY.NS', 'HAL.NS', 'BEL.NS', 'IRFC.NS', 'LICI.NS', 'DLF.NS', 'LODHA.NS', 'GODREJPROP.NS', 'OBEROIRLTY.NS', 'PRESTIGE.NS', 'NYKAA.NS', 'DELHIVERY.NS', 'INDIGO.NS', 'ANGELONE.NS', 'IRB.NS', 'NCC.NS', 'KNRCON.NS', 'ASHOKA.NS', 'POLYCAB.NS', 'KEI.NS', 'HAVELLS.NS', 'VOLTAS.NS', 'APLAPOLLO.NS', 'PAGEIND.NS', 'RADICO.NS', 'VSTIND.NS', 'GODFRYPHLP.NS', 'ZEEL.NS', 'SUNTV.NS', 'RAYMOND.NS', 'ASTRAL.NS', 'SUPREMEIND.NS']

TAIWAN_TWSE = ['2330.TW', '2454.TW', '2303.TW', '2308.TW', '3711.TW', '2344.TW', '2379.TW', '3034.TW', '2337.TW', '3481.TW', '2360.TW', '2317.TW', '4938.TW', '2382.TW', '2324.TW', '2356.TW', '2353.TW', '2357.TW', '2347.TW', '2301.TW', '2376.TW', '2412.TW', '3045.TW', '4904.TW', '2891.TW', '2881.TW', '2882.TW', '2884.TW', '2886.TW', '2887.TW', '2892.TW', '2880.TW', '2801.TW', '5880.TW', '5876.TW', '1301.TW', '1303.TW', '1326.TW', '6505.TW', '2002.TW', '2049.TW', '2395.TW', '2327.TW', '3044.TW', '4958.TW', '3037.TW', '1216.TW', '2912.TW', '9904.TW', '3008.TW', '2474.TW', '2498.TW', '2603.TW', '2609.TW', '2615.TW', '2618.TW', '2610.TW', '2633.TW', '1101.TW', '1102.TW', '1504.TW', '1605.TW', '2408.TW', '9921.TW', '9914.TW', '2371.TW']

AUSTRALIA_ASX = ['BHP.AX', 'CBA.AX', 'CSL.AX', 'ANZ.AX', 'WBC.AX', 'NAB.AX', 'WES.AX', 'WOW.AX', 'MQG.AX', 'RIO.AX', 'FMG.AX', 'TLS.AX', 'TCL.AX', 'GMG.AX', 'ALL.AX', 'REA.AX', 'SEK.AX', 'COL.AX']

AUSTRALIA_ASX_EXT = ['IAG.AX', 'SUN.AX', 'QBE.AX', 'AMP.AX', 'CGF.AX', 'MQG.AX', 'BEN.AX', 'BOQ.AX', 'CBA.AX', 'CPU.AX', 'S32.AX', 'OZL.AX', 'ILU.AX', 'IGO.AX', 'LYC.AX', 'PLS.AX', 'MIN.AX', 'EVN.AX', 'NST.AX', 'RRL.AX', 'RMS.AX', 'SFR.AX', 'NIC.AX', 'AKE.AX', 'WDS.AX', 'STO.AX', 'ALD.AX', 'APA.AX', 'ORG.AX', 'VEA.AX', 'SHL.AX', 'RMD.AX', 'MPL.AX', 'NHF.AX', 'HLS.AX', 'PHL.AX', 'COH.AX', 'FPH.AX', 'IDX.AX', 'JBH.AX', 'LOV.AX', 'PMV.AX', 'DMP.AX', 'TWE.AX', 'BXB.AX', 'WES.AX', 'WOW.AX', 'COL.AX', 'MTS.AX', 'APE.AX', 'QAN.AX', 'AZJ.AX', 'CWY.AX', 'ORI.AX', 'IPL.AX', 'AMC.AX', 'CAR.AX', 'REA.AX', 'CTD.AX', 'IEL.AX', 'ARB.AX', 'XRO.AX', 'WTC.AX', 'ALU.AX', 'TNE.AX', 'NXT.AX', 'AUB.AX', 'GPT.AX', 'DXS.AX', 'SGP.AX', 'VCX.AX', 'CIP.AX', 'GMG.AX', 'CHC.AX', 'GQG.AX', 'AGL.AX', 'AST.AX']

CANADA_TSX = ['RY.TO', 'TD.TO', 'BNS.TO', 'BMO.TO', 'CM.TO', 'CNR.TO', 'CP.TO', 'ENB.TO', 'TRP.TO', 'SU.TO', 'CNQ.TO', 'ATD.TO', 'MG.TO', 'ABX.TO', 'AEM.TO', 'SHOP.TO', 'GIB-A.TO']

CANADA_TSX_EXT = ['CVE.TO', 'ARX.TO', 'TOU.TO', 'BTE.TO', 'ERF.TO', 'CPX.TO', 'PPL.TO', 'ALA.TO', 'NPI.TO', 'KEY.TO', 'WCP.TO', 'TVE.TO', 'MEG.TO', 'VII.TO', 'POU.TO', 'BIR.TO', 'AAV.TO', 'GEI.TO', 'MFC.TO', 'SLF.TO', 'GWO.TO', 'IAG.TO', 'IFC.TO', 'EQB.TO', 'CWB.TO', 'LB.TO', 'FFH.TO', 'BCE.TO', 'T.TO', 'RCI-B.TO', 'CLS.TO', 'MDA.TO', 'ENGH.TO', 'CSU.TO', 'DSG.TO', 'TIXT.TO', 'DOL.TO', 'L.TO', 'MRU.TO', 'EMP-A.TO', 'SAP.TO', 'ATD.TO', 'QSR.TO', 'DOO.TO', 'WCN.TO', 'TFII.TO', 'CAE.TO', 'FSV.TO', 'GFL.TO', 'STN.TO', 'WSP.TO', 'ATS.TO', 'TIH.TO', 'SIS.TO', 'BDT.TO', 'H.TO', 'FTS.TO', 'EMA.TO', 'AQN.TO', 'BIP-UN.TO', 'BEP-UN.TO', 'BAM.TO', 'BN.TO', 'FCR-UN.TO', 'HR-UN.TO', 'WFG.TO', 'IVN.TO', 'K.TO', 'LUN.TO', 'FM.TO', 'ERO.TO', 'FNV.TO', 'AEM.TO', 'ABX.TO', 'ACQ.TO', 'CXW.TO', 'CIGI.TO']

# ALL_AZIONI: 3072 totali
ALL_AZIONI = list(dict.fromkeys(
    USA_SP500 + USA_MIDCAP + USA_RUSSELL2000 + USA_SMALLCAP_SP600 + UK_FTSE100 + UK_FTSE250 + GERMANY_DAX + GERMANY_MDAX + FRANCE_CAC40 + FRANCE_MIDCAP + ITALY_MIB + SPAIN_IBEX + SWISS_SMI + NETHERLANDS_AEX + SWEDEN_OMXS + NORWAY_OBX + DENMARK_OMXC + FINLAND_OMXH + BELGIUM_BEL20 + AUSTRIA_ATX + PORTUGAL_PSI + JAPAN_NIKKEI + JAPAN_TOPIX_EXT + HK_HANGSENG + KOREA_KOSPI + BRAZIL_IBOVESPA + INDIA_NIFTY + TAIWAN_TWSE + AUSTRALIA_ASX + AUSTRALIA_ASX_EXT + CANADA_TSX + CANADA_TSX_EXT
))

ETF_US_BROAD = ['SPY', 'IVV', 'VOO', 'SPLG', 'SPTM', 'SCHB', 'SCHX', 'ITOT', 'VV', 'MGC', 'MGK', 'MGV', 'SPYG', 'SPYV', 'SPYD', 'QQQ', 'QQQM', 'ONEQ', 'DIA', 'MDY', 'IJH', 'VO', 'SPMD', 'SCHM', 'IWM', 'IJR', 'VB', 'SPSM', 'SCHA', 'VTWO', 'VTI', 'VXF', 'CQQQ', 'IWF', 'IWD', 'IUSG', 'IUSV', 'VOOG', 'VOOV', 'IWN', 'IWO', 'IWP', 'IWS', 'IWR', 'VONE', 'VTHR', 'RSP', 'COWZ', 'CALF', 'TTAC', 'ESGU', 'SUSA']

ETF_US_SECTOR = ['XLF', 'XLK', 'XLE', 'XLV', 'XLI', 'XLU', 'XLP', 'XLB', 'XLRE', 'XLY', 'XLC', 'VFH', 'VGT', 'VDE', 'VHT', 'VIS', 'VPU', 'VDC', 'VAW', 'VCR', 'VOX', 'IYF', 'IYH', 'IYE', 'IYM', 'IYC', 'IYJ', 'IYW', 'IYZ', 'SOXX', 'SMH', 'FTEC', 'FDN', 'XITK', 'IBB', 'XBI', 'ARKG', 'IDNA', 'GNOM', 'IHI', 'IHF', 'IHE', 'FBT', 'PSCH', 'HACK', 'CIBR', 'BUG', 'BOTZ', 'ROBO', 'AIQ', 'IGPT', 'ICLN', 'QCLN', 'FAN', 'SMOG', 'DRIV', 'IDRV', 'FINX', 'IPAY', 'ARKK', 'ARKW', 'ARKF', 'ARKQ', 'CLOU', 'SKYY', 'WCLD', 'HERO', 'METV', 'GDX', 'GDXJ', 'SIL', 'XOP', 'OIH', 'XME', 'PICK', 'COPX', 'LIT', 'REMX', 'MOO', 'PBS', 'ITA', 'PPA', 'XAR', 'XRT', 'RTH', 'PBJ', 'KBE', 'KRE', 'IAI', 'KBWB', 'KWEB', 'FXI', 'MCHI', 'PHO', 'GRID', 'WOOD']

ETF_US_BONDS = ['AGG', 'BND', 'SPAB', 'TLT', 'IEF', 'SHY', 'GOVT', 'SCHO', 'SCHR', 'SCHZ', 'BIL', 'SGOV', 'USFR', 'FLRN', 'CLTL', 'LQD', 'VCIT', 'VCLT', 'BIV', 'BLV', 'IGSB', 'IGIB', 'CORP', 'SPBO', 'VCSH', 'BSV', 'SPSB', 'SCHI', 'HYG', 'JNK', 'SJNK', 'USHY', 'HYDB', 'FALN', 'ANGL', 'HYXF', 'TIP', 'SCHP', 'SPIP', 'VTIP', 'STIP', 'RINF', 'MUB', 'VTEB', 'TFI', 'SUB', 'SHYD', 'HYMB', 'HYD', 'CMF', 'ITM', 'FLOT', 'NEAR', 'SHV', 'JPST', 'MINT', 'ICSH', 'IGOV', 'BWX', 'BNDX', 'IAGG', 'EMB', 'VWOB', 'PCY', 'EBND', 'EMHY', 'BKLN', 'SRLN', 'SLQD', 'SHYG', 'SPLB', 'SPMB', 'PFF', 'PGX', 'PFFD', 'FPE', 'VRP', 'CWB', 'ICVT']

ETF_US_INTL = ['VEA', 'VWO', 'EFA', 'EEM', 'IEFA', 'IEMG', 'VGK', 'VPL', 'VEU', 'VXUS', 'IXUS', 'ACWI', 'ACWX', 'SCZ', 'GWX', 'EFV', 'EFG', 'EMXC', 'EEMS', 'XSOE', 'EWJ', 'EWY', 'EWT', 'EWH', 'EWM', 'EWS', 'EWA', 'FLJP', 'FLKR', 'FLTW', 'EWG', 'EWU', 'EWQ', 'EWI', 'EWP', 'EWN', 'EWD', 'EWO', 'EFNL', 'GREK', 'EWZ', 'EWC', 'EWW', 'EZA', 'TUR', 'VNM', 'EDEN', 'ENOR', 'EPHE', 'ECH', 'EPU', 'EIDO', 'THD', 'DXJ', 'HEWJ', 'DBJP', 'HEDJ', 'DBEU', 'HEFA', 'SPEM', 'SCHE', 'DEM', 'EDIV', 'DGS', 'FNDE', 'VYMI', 'VIGI', 'EMQQ', 'KBA', 'CNYA']

ETF_US_FACTOR = ['MTUM', 'JMOM', 'PDP', 'IMOM', 'VLUE', 'IUSV', 'SPVU', 'VONV', 'IVOV', 'SLYV', 'VBR', 'QVAL', 'IVAL', 'GVAL', 'QUAL', 'FQAL', 'JPUS', 'USMV', 'SPLV', 'LGLV', 'SPHD', 'FDLO', 'SIZE', 'SMMV', 'XMLV', 'DGRO', 'SDY', 'DVY', 'VIG', 'VYM', 'SCHD', 'NOBL', 'HDV', 'DGRW', 'PEY', 'FDL', 'CDC', 'RDIV', 'DIVO', 'RDVY', 'EFAV', 'EEMV', 'ACWV', 'INTF', 'LRGF', 'SMLF', 'DFAC', 'DFAX', 'PKW', 'TTAC', 'MOAT']

ETF_US_REAL_COMM = ['GLD', 'IAU', 'SGOL', 'GLDM', 'OUNZ', 'BAR', 'SLV', 'PPLT', 'PALL', 'DBC', 'GSG', 'PDBC', 'COMT', 'FTGC', 'BCI', 'DJP', 'CPER', 'USO', 'UNG', 'USL', 'BNO', 'WEAT', 'CORN', 'SOYB', 'DBA', 'TAGS', 'VNQ', 'IYR', 'SCHH', 'USRT', 'ICF', 'RWR', 'REET', 'REM', 'MORT', 'KBWY', 'INDS', 'SRVR', 'REZ', 'BBRE', 'HOMZ']

ETF_EUROPE_L = ['IWDA.L', 'SWDA.L', 'CSPX.L', 'IUSA.L', 'SSAC.L', 'ISAC.L', 'SWRD.L', 'HMWO.L', 'XDWD.L', 'INRG.L', 'VEUR.L', 'IEUX.L', 'IEEM.L', 'EIMI.L', 'IUSN.L', 'VAPX.L', 'VJPN.L', 'IFSB.L', 'IBTS.L', 'IBTM.L', 'IBCX.L', 'IAGG.L', 'IHYG.L', 'IWFV.L', 'IQLT.L', 'IWMO.L', 'IWSZ.L', 'IUIT.L', 'IPRP.L', 'XESC.L', 'XUHY.L', 'IDTG.L', 'IDTP.L', 'IGLN.L', 'IGLT.L', 'SLXX.L', 'VWRL.L', 'VUSA.L', 'VUKE.L', 'VMID.L', 'VFEM.L', 'VHYL.L', 'VAGP.L', 'VAGS.L', 'VERX.L', 'VAPX.L', 'VJPN.L', 'SPY5.L', 'SPPW.L', 'SPXS.L', 'GLTL.L', 'ZPRR.L', 'ZPRS.L', 'ZPRV.L', 'ZPRE.L', 'SPGB.L', 'SPIB.L', 'WDIV.L', 'EQQQ.L', 'MXWU.L', 'PBUS.L', 'PBEU.L', 'PBEE.L', 'HGEM.L', 'HUKX.L', 'HPSS.L', 'HPUS.L', 'HPEU.L', 'HJPN.L', 'WQCD.L', 'WSML.L', 'WTCH.L', 'SGLD.L', 'PHAU.L', 'PHAG.L', 'PHPT.L', 'AGGG.L', 'AIGA.L', 'LGIT.L', 'LGIG.L', 'LGIS.L', 'LGIU.L']

ETF_EUROPE_DE = ['EXS1.DE', 'EXW1.DE', 'EXSA.DE', 'EXUS.DE', 'SXR8.DE', 'SXRM.DE', 'SXRJ.DE', 'SXRD.DE', 'SXRL.DE', 'EUNL.DE', 'EUN2.DE', 'EUN3.DE', 'EUN4.DE', 'EUNA.DE', 'EUNB.DE', 'IS3N.DE', 'IS3S.DE', 'QDVE.DE', 'QDVG.DE', 'QDVH.DE', 'EXV1.DE', 'EXV3.DE', 'EXV6.DE', 'EXV7.DE', 'EXV8.DE', 'EXXT.DE', 'EXHD.DE', 'IQQQ.DE', 'IQQH.DE', 'IQQE.DE', 'IQQR.DE', 'IWDE.DE', 'IQQW.DE', 'SXRS.DE', 'SXRU.DE', 'IBCD.DE', 'IBCI.DE', 'ISAC.DE', 'DBXD.DE', 'DBXT.DE', 'DBXJ.DE', 'DBXK.DE', 'DBXN.DE', 'DBXE.DE', 'DBXS.DE', 'XDWD.DE', 'XNAS.DE', 'DXGE.DE', 'XDWE.DE', 'XDWG.DE', 'XDWH.DE', 'XDWT.DE', 'XESC.DE', 'XMLD.DE', 'XGLE.DE', 'XGSH.DE', 'XUHY.DE', 'VWCE.DE', 'VGWL.DE', 'VJPA.DE', 'VEUR.DE', 'VUSA.DE', 'VFEM.DE', 'VHYL.DE', 'LYPS.DE', 'LYY6.DE', 'LCWL.DE', 'LCEU.DE', 'LCUS.DE', 'LYPA.DE', 'LYYW.DE', 'LYYA.DE', 'SPY5.DE', 'ZPRS.DE', 'ZPRR.DE', 'ZPRV.DE', 'ZPRE.DE', 'WDIV.DE']

ETF_EUROPE_AS = ['IWDA.AS', 'EMIM.AS', 'IUSN.AS', 'EIMI.AS', 'SWRD.AS', 'CSNDX.AS', 'CSSPX.AS', 'ISAC.AS', 'IQQQ.AS', 'IBTS.AS', 'IBCX.AS', 'IAGG.AS', 'IHYG.AS', 'INRG.AS', 'IUIT.AS', 'QDVE.AS', 'QDVG.AS', 'IWFV.AS', 'IQLT.AS', 'IWMO.AS', 'VWRL.AS', 'VUSA.AS', 'VEUR.AS', 'VFEM.AS', 'VHYL.AS', 'VGWL.AS', 'VAGP.AS', 'VAGS.AS', 'VERX.AS', 'VJPN.AS', 'VAPX.AS', 'VWRP.AS', 'LYPS.AS', 'LCWD.AS', 'LCEU.AS', 'LCUS.AS', 'PAEEM.AS', 'LYYW.AS', 'XDWD.AS', 'MEUD.AS', 'XAIX.AS', 'SPYW.AS', 'WLDV.AS']

ETF_EUROPE_PA = ['CW8.PA', 'E500.PA', 'LCWD.PA', 'LCEU.PA', 'LCUS.PA', 'AEEM.PA', 'PAEEM.PA', 'PAASI.PA', 'WPEA.PA', 'AMERP.PA', 'LYYW.PA', 'LYYA.PA', 'EWLD.PA', 'ESE.PA', 'MSWO.PA', 'MWRD.PA', 'LU0.PA', 'LYPS.PA', 'LVC.PA', 'INRG.PA', 'IQQQ.PA', 'EUNL.PA', 'IS3N.PA', 'EEX.PA', 'BNX.PA']

ETF_EUROPE_MI = ['SWDA.MI', 'CSPX.MI', 'EIMI.MI', 'IWDA.MI', 'IUSA.MI', 'SSAC.MI', 'IQQQ.MI', 'IBTS.MI', 'IBCX.MI', 'ISAC.MI', 'SXRL.MI', 'IS3N.MI', 'IHYG.MI', 'IAGG.MI', 'QDVE.MI', 'IWFV.MI', 'IQLT.MI', 'INRG.MI', 'VWRL.MI', 'VUSA.MI', 'VEUR.MI', 'VFEM.MI', 'VGWL.MI', 'VHYL.MI', 'VAPX.MI', 'VJPN.MI', 'EXW1.MI', 'XDWD.MI', 'DBXT.MI', 'LYPS.MI', 'LCWD.MI', 'LCEU.MI', 'LCUS.MI', 'AEEM.MI', 'PAEEM.MI']

ETF_EUROPE_SW = ['SWRD.SW', 'SSAC.SW', 'CSPX.SW', 'IWDA.SW', 'EIMI.SW', 'IQQQ.SW', 'IBTS.SW', 'IBCX.SW', 'IAGG.SW', 'SXRL.SW', 'IHYG.SW', 'IS3N.SW', 'INRG.SW', 'VWRL.SW', 'VHYL.SW', 'VUSA.SW', 'VEUR.SW', 'VFEM.SW', 'IEAG.SW', 'IGLN.SW', 'SGLD.SW']


ETF_US_THEMATIC = ['CIBR', 'HACK', 'BUG', 'WCLD', 'CLOU', 'SKYY', 'ROBO', 'BOTZ', 'IRBO', 'AIQ', 'THNQ', 'FIVG', 'NXTG', 'ICLN', 'QCLN', 'DRIV', 'IDRV', 'LIT', 'BATT', 'GRID', 'ACES', 'ESPO', 'HERO', 'ARKK', 'ARKG', 'ARKW', 'ARKF', 'ARKQ', 'AWAY', 'UFO', 'BETZ', 'GRNB', 'KRBN', 'NANR', 'HTEC', 'METV', 'CHAT', 'AIOT', 'DTCR', 'SNSR', 'PAVE', 'IFRA', 'IGF', 'TOLZ', 'FAN', 'RNRG', 'CNRG', 'PHO', 'KCCA', 'ERTH']

ETF_US_DIVIDEND = ['VIG', 'DGRO', 'SCHD', 'HDV', 'DVY', 'VYM', 'SPHD', 'SDY', 'FVD', 'DGRW', 'FDVV', 'PEY', 'DHS', 'RDVY', 'REGL', 'SDOG', 'DLN', 'NOBL', 'DIVO', 'FPXI', 'IDVO', 'IHDG', 'VIGI', 'VYMI', 'PID', 'DWX', 'EFAD', 'EDIV', 'DVYE']

ETF_US_INCOME = ['JEPI', 'JEPQ', 'XYLD', 'QYLD', 'RYLD', 'NUSI', 'GPIQ', 'GPIX', 'SPYI', 'QQQI', 'DIVO', 'KNG', 'HNDL', 'ETV', 'UTF', 'PDI', 'PTY', 'GOF', 'RFI', 'RQI', 'PFFD', 'PFXF', 'PFF', 'FPE']

ETF_US_ESG = ['ESGV', 'ESGU', 'SUSL', 'VSGX', 'DSI', 'SUSA', 'USSG', 'NULC', 'NULV', 'NULG', 'NUSC', 'NUMV', 'EFAX', 'ESGD', 'ESGE', 'CRBN', 'LOWC', 'SMOG', 'SPYX', 'VEGN', 'JUST', 'NACP', 'WOMN', 'BIBL', 'VOTE']

ETF_US_BONDS_CORP = ['LQD', 'VCIT', 'VCSH', 'USIG', 'SPBO', 'IGIB', 'IGSB', 'QLTA', 'FLOT', 'NEAR', 'MINT', 'JPST', 'GSY', 'ICSH', 'ULST', 'CLTL', 'SGOV', 'SHV', 'GBIL', 'TFLO']

ETF_US_BONDS_HY = ['HYG', 'JNK', 'USHY', 'SHYG', 'HYLB', 'HYEM', 'BSJQ', 'BSJR', 'SJNK', 'HYLS', 'GHYB']

ETF_US_BONDS_GOVT = ['VTIP', 'SCHP', 'TIP', 'STIP', 'FISR', 'LTPZ', 'TIPX', 'MUB', 'SUB', 'VTEB', 'TFI', 'HYD', 'MUNI', 'BNDX', 'EMB', 'PCY', 'EMLC', 'LEMB', 'IGOV', 'BWX']

ETF_US_COUNTRY = ['EWJ', 'EWG', 'EWU', 'EWC', 'EWL', 'EWA', 'EWH', 'EWS', 'EWY', 'EWT', 'EWZ', 'EWW', 'EWI', 'EWP', 'EWQ', 'EWK', 'EWN', 'EWD', 'EWO', 'MCHI', 'INDA', 'KWEB', 'EZA', 'NORW', 'THD', 'TUR', 'ARGT', 'GXC', 'FXI', 'CNYA', 'INDY', 'FLBR', 'EPHE', 'EPOL', 'ENZL', 'EIDO', 'ECH', 'EDEN', 'EFNL', 'ENOR']

ETF_US_MULTI_FACTOR = ['QUAL', 'USMV', 'ACWV', 'EEMV', 'EFAV', 'SIZE', 'LRGF', 'INTF', 'DGRS', 'FVAL', 'FQAL', 'FMAT', 'FCOM', 'FDIG', 'FTEK', 'FHLC', 'FCPI', 'DFAC', 'DFIC', 'DFAI', 'DFEM', 'DFSV', 'DFAS', 'DFLV', 'AVUS', 'AVDE', 'AVEM', 'AVUV', 'AVDV']

ETF_US_REAL_EXTRA = ['VNQ', 'SCHH', 'USRT', 'RWR', 'ICF', 'MORT', 'REM', 'SRET', 'KBWY', 'HOMZ', 'REZ', 'INDS', 'PPTY', 'BBRE', 'REET', 'IFGL', 'RWX', 'VNQI', 'HAUZ']

ETF_EUROPE_AS_EXT = ['VWCE.AS', 'VUAA.AS', 'VUSA.AS', 'VEUR.AS', 'VJPN.AS', 'VHYL.AS', 'VGWD.AS', 'VAGF.AS', 'AGGH.AS', 'CORPS.AS', 'EXUS.AS', 'CNDX.AS', 'IGLO.AS', 'IUSQ.AS', 'IQQA.AS', 'IQQH.AS', 'IQQE.AS', 'SPPW.AS', 'SPYW.AS', 'IS3R.AS', 'XMME.AS', 'MEUD.AS', 'LYPS.AS', 'LCUK.AS', 'LCUJ.AS', 'LCUE.AS', 'VFEA.AS', 'VERD.AS', 'VFEM.AS', 'VAGP.AS']

ETF_EUROPE_PA_EXT = ['VWCE.PA', 'VUAA.PA', 'VUSA.PA', 'PANX.PA', 'PCEU.PA', 'PUST.PA', 'PUSP.PA', 'ESGE.PA', 'GWT.PA', 'MWRD.PA', 'MAWO.PA', 'LCWD.PA', 'LCEU.PA', 'SPPW.PA', 'SPYW.PA', 'PAEEM.PA', 'AMUN.PA', 'BNXI.PA', 'LUPA.PA', 'AAXJ.PA', 'ASWD.PA', 'IQQQ.PA', 'WLDH.PA', 'XDWH.PA', 'APXJ.PA']

ETF_EUROPE_MI_EXT = ['VWCE.MI', 'VUAA.MI', 'VUSA.MI', 'VEUR.MI', 'VJPN.MI', 'AGGH.MI', 'CORPS.MI', 'EXUS.MI', 'CNDX.MI', 'SADV.MI', 'XDWH.MI', 'XDWT.MI', 'XDWB.MI', 'SPPW.MI', 'SPYW.MI', 'LCWD.MI', 'VHYL.MI', 'VGWD.MI', 'VAGF.MI', 'IQQQ.MI', 'MEUD.MI', 'LYPS.MI', 'IS3R.MI', 'XMME.MI', 'PAEEM.MI', 'AEEM.MI', 'WPEA.MI', 'IGLO.MI', 'IUSQ.MI']

ETF_EUROPE_DE_EXT = ['VWCE.DE', 'VUAA.DE', 'CNDX.DE', 'XDWH.DE', 'XDWT.DE', 'XDWB.DE', 'XDWU.DE', 'XDWE.DE', 'EXH1.DE', 'EXH2.DE', 'EXH3.DE', 'EXH4.DE', 'EXH5.DE', 'EXH6.DE', 'XMME.DE', 'EXSC.DE', 'EXIP.DE', 'EXSH.DE', 'MEUD.DE', 'DBXD.DE', 'DXET.DE', 'LYPS.DE', 'SPPW.DE', 'SPYW.DE', 'IS3R.DE', 'AGGH.DE', 'CORPS.DE', 'IUSQ.DE', 'LCWD.DE', 'LCEU.DE', 'VHYL.DE', 'VGWD.DE', 'VAGF.DE', 'VFEA.DE', 'VERD.DE', 'PAEEM.DE', 'SADV.DE', 'JREG.DE', 'XDPD.DE', 'XDPU.DE']

ETF_EUROPE_L_EXT = ['VWCE.L', 'VUAA.L', 'VEUR.L', 'VJPN.L', 'VHYL.L', 'VGWD.L', 'VAGF.L', 'AGGH.L', 'CORPS.L', 'SPPW.L', 'SPYW.L', 'LCWD.L', 'LCEU.L', 'IS3R.L', 'XMME.L', 'MEUD.L', 'LYPS.L', 'SADV.L', 'PAEEM.L', 'CNDX.L', 'IGLO.L', 'DBXD.L', 'VFEA.L', 'VERD.L', 'VFEM.L']


ETF_EUROPE_INVESCO = ['PAGG.L', 'PBUS.L', 'PBEE.L', 'PGBP.L', 'PKOB.L', 'PSRW.L', 'PLSA.L', 'PKLM.L', 'PEAU.L', 'PJPN.L', 'PCNS.L', 'PFIG.L', 'PEMD.L', 'PHEM.L', 'PSMV.L', 'PRAE.L', 'PAGG.DE', 'PBUS.DE', 'PBEE.DE', 'PSRW.DE', 'PEMD.DE', 'PHEM.DE', 'PEAU.DE', 'PAGG.MI', 'PBUS.MI', 'PBEE.MI', 'PAGG.AS', 'PBEE.AS']

ETF_EUROPE_VANECK = ['SMGB.DE', 'MOTE.DE', 'MVEU.DE', 'MVEM.DE', 'TBLU.DE', 'MOAT.DE', 'MULT.DE', 'VANX.DE', 'VFLQ.DE', 'EMQQ.L', 'SMGB.L', 'MOTE.L', 'MVEU.L', 'MVEM.L', 'HURE.L', 'HULK.L', 'NUCL.L', 'MVDX.L', 'SMGB.MI', 'MOTE.MI', 'EMQQ.AS', 'SMGB.AS']

ETF_EUROPE_FIDELITY_UCITS = ['FGQD.L', 'FUSD.L', 'FWWG.L', 'FGUI.L', 'FSWD.L', 'FEMF.L', 'FEMS.L', 'FUSA.L', 'FDNI.L', 'FCSH.L', 'FGQD.DE', 'FUSD.DE', 'FWWG.DE', 'FUSA.DE', 'FEMS.DE', 'FGQD.MI', 'FUSD.MI', 'FGQD.AS', 'FUSD.AS']

ETF_EUROPE_JPMORGAN = ['JGPI.L', 'JGPI.DE', 'JGPI.MI', 'JGPI.AS', 'JPEA.L', 'JPUS.L', 'JPED.L', 'JPEM.L', 'JPGL.L', 'JPHU.L', 'JNKI.L', 'JPEA.DE', 'JPUS.DE', 'JPEM.DE', 'JGPI.PA', 'JPUS.MI', 'JPEA.MI']

ETF_EUROPE_FRANKLIN = ['FUSA.L', 'FEMS.L', 'FLXE.L', 'FWRA.L', 'FLCA.L', 'FLJP.L', 'FLXG.L', 'FLAR.L', 'FUSA.DE', 'FEMS.DE', 'FLXE.DE', 'FWRA.DE', 'FUSA.AS', 'FEMS.AS', 'FUSA.MI']

ETF_EUROPE_WISDOMTREE_EQ = ['WTAI.L', 'WTEM.L', 'WQCG.L', 'WTEF.L', 'WTDG.L', 'WGBL.L', 'WJPN.L', 'WEUR.L', 'WEMG.L', 'WTAI.DE', 'WTEM.DE', 'WQCG.DE', 'WTEF.DE', 'WTAI.AS', 'WTAI.MI']

ETF_EUROPE_AMUNDI_EXT = ['EWLD.PA', 'EPAH.PA', 'PAASI.PA', 'AASI.PA', 'CEIA.PA', 'AEME.PA', 'AAPL.PA', 'CE9.PA', 'AESG.PA', 'CIN.PA', 'AFRI.PA', 'MFRA.PA', 'AFRA.PA', 'EWLD.MI', 'EPAH.MI', 'AESG.MI', 'EWLD.AS', 'EPAH.AS', 'EWLD.DE', 'AESG.DE', 'PAASI.DE']

ETF_EUROPE_XTRACKERS_EXT = ['DBZB.DE', 'DBXT.DE', 'DBXJ.DE', 'XMEU.DE', 'XUTD.DE', 'XREA.DE', 'XCSR.DE', 'XGLE.DE', 'XGSH.DE', 'XGHG.DE', 'XWSC.DE', 'X014.DE', 'XMEM.DE', 'XWLD.DE', 'XMLD.DE', 'DBZB.L', 'DBXT.L', 'XMEM.L', 'XWLD.L', 'XREA.L', 'DBZB.MI', 'XMEM.MI']

ETF_EUROPE_ISHARES_UCITS_EXT = ['IBTS.L', 'IBCX.L', 'EMHG.L', 'IBTE.L', 'IBTU.L', 'IBTM.L', 'ISF.L', 'INXG.L', 'SLXX.L', 'IGLH.L', 'IGLS.L', 'IS3N.L', 'IQSA.L', 'IQSJ.L', 'IQSE.L', 'ERNS.L', 'ERND.L', 'IRCP.L', 'IERN.L', 'IBTS.DE', 'IBCX.DE', 'EMHG.DE', 'IBTE.DE', 'IBTU.DE', 'IS3N.DE', 'IBTS.MI', 'IBCX.MI', 'IBTS.AS', 'IBCX.AS', 'EMHG.AS']

ETF_EUROPE_GLOBALX_UCITS = ['SDIV.L', 'TECH.L', 'CLND.L', 'HLTH.L', 'FINA.L', 'INFU.L', 'SEMI.L', 'PAVE.L', 'LIT.L', 'BOTZ.L', 'SDIV.DE', 'TECH.DE', 'SEMI.DE', 'LIT.DE', 'BOTZ.DE']

ETF_EUROPE_SPDR_UCITS_EXT = ['SPYL.L', 'SPY5.L', 'SPFE.L', 'SPFD.L', 'SPFA.L', 'ZPRI.L', 'SPEU.L', 'SPEM.L', 'ZPRS.L', 'SPYL.DE', 'SPY5.DE', 'SPFE.DE', 'SPEU.DE', 'SPEM.DE', 'SPYL.MI', 'SPY5.MI', 'SPYL.AS', 'SPY5.AS']

# ETF europei ACC — categorie mancanti (aggiunto 2026-06-14)
ETF_EUROPE_ACC_CORE = [
    # ── iShares S&P 500 Settori ACC (tech/fin/health già presenti) ────────────
    'QDVJ.DE', 'QDVK.DE', 'QDVL.DE', 'QDVM.DE', 'QDVN.DE', 'QDVO.DE',  # Cons.Disc, Energy, Materials, Utilities, Cons.Staples, Real Estate
    'QDVJ.L',  'QDVK.L',  'QDVL.L',  'QDVM.L',  'QDVN.L',  'QDVO.L',
    # ── iShares Tematici UCITS ACC ────────────────────────────────────────────
    'DGTL.L',                  # Digitalisation UCITS ETF
    'HEAL.L',  'HEAL.DE',                  # Global Healthcare Innovation
    'ECAR.L',  'ECAR.DE',                  # Electric Vehicles & Driving Tech
    'RBOT.L',  'RBOT.DE',                  # Automation & Robotics
    'LOCK.L',  'LOCK.DE',                  # Digital Security
    'CLMA.L',  'CLMA.DE',                  # MSCI Global Climate Change
    'WTAI.DE', 'WTAI.AS',                  # WisdomTree AI (già .L in WISDOMTREE_EQ)
    # ── iShares Factor / Smart Beta ACC ──────────────────────────────────────
    'IWVL.L',                  # MSCI World Value Factor
    'IUVL.L',                              # MSCI USA Value Factor
    'IWFS.L',  'IWFS.DE',                  # MSCI World Multifactor
    'MVOL.L',  'MVOL.DE',                  # MSCI World Minimum Volatility
    'UIMV.L',                              # MSCI USA Minimum Volatility
    'SUSW.L',  'SUSW.DE',                  # MSCI World SRI
    'PAWD.L',  'PAWD.DE',                  # MSCI World ESG Enhanced
    'SDEQ.L',  'SDEQ.DE',                  # MSCI World ESG Screened
    # ── iShares Europa ACC ────────────────────────────────────────────────────
    'IEUS.L',  'IEUS.DE',                  # Core MSCI Europe
    'CSUK.L',                              # Core FTSE 100 (ACC)
    # ── iShares Emerging Markets ACC ─────────────────────────────────────────
    'EMIM.L',  'EMIM.DE',                  # Core MSCI EM IMI
    'INDI.L',  'INDI.DE',                  # MSCI India
    'EEMA.L',                              # MSCI EM Asia
    'AIAI.L',                              # MSCI China A (ACC)
    # ── iShares Fixed Income ACC ─────────────────────────────────────────────
    'IEAC.L',  'IEAC.DE',                  # Core Euro Corporate Bond
    'IEAG.L',                  # Core Euro Government Bond
    'IEGE.L',                              # Euro Government Bond 1-3yr
    'AGIH.L',  'AGIH.DE',                  # Core Global Aggregate Bond EUR Hdg
    'GOVS.L',                              # USD Government Bond 1-3yr
    # ── Amundi/Lyxor extra ACC ───────────────────────────────────────────────
    'LWQ.PA',                              # Lyxor MSCI World Quality Factor
    'WLDD.PA', 'WLDD.DE',                  # Lyxor Core MSCI World (ACC)
    'MWDG.PA',                             # Amundi MSCI World Daily Hedged EUR
    # ── SPDR Small Cap ACC ───────────────────────────────────────────────────
    'ZPRX.DE',      # MSCI World Small Cap
    # ── Xtrackers extra ACC ───────────────────────────────────────────────────
    'XXSC.L',                              # MSCI World Small Cap (Xtrackers)
    'XMEU.L',  'XMEU.DE',                  # MSCI Europe (ACC)
    # ── HSBC extra ACC ───────────────────────────────────────────────────────
    # MSCI World (ACC) — .L già presente
]

# ALL_ETF: ~1190 totali (dopo dedup ISIN)
ALL_ETF = list(dict.fromkeys(
    ETF_US_BROAD + ETF_US_SECTOR + ETF_US_BONDS + ETF_US_INTL + ETF_US_FACTOR + ETF_US_REAL_COMM +
    ETF_EUROPE_L + ETF_EUROPE_DE + ETF_EUROPE_AS + ETF_EUROPE_PA + ETF_EUROPE_MI + ETF_EUROPE_SW +
    ETF_US_THEMATIC + ETF_US_DIVIDEND + ETF_US_INCOME + ETF_US_ESG + ETF_US_BONDS_CORP +
    ETF_US_BONDS_HY + ETF_US_BONDS_GOVT + ETF_US_COUNTRY + ETF_US_MULTI_FACTOR + ETF_US_REAL_EXTRA +
    ETF_EUROPE_AS_EXT + ETF_EUROPE_PA_EXT + ETF_EUROPE_MI_EXT + ETF_EUROPE_DE_EXT + ETF_EUROPE_L_EXT +
    ETF_EUROPE_INVESCO + ETF_EUROPE_VANECK + ETF_EUROPE_FIDELITY_UCITS + ETF_EUROPE_JPMORGAN +
    ETF_EUROPE_FRANKLIN + ETF_EUROPE_WISDOMTREE_EQ + ETF_EUROPE_AMUNDI_EXT + ETF_EUROPE_XTRACKERS_EXT +
    ETF_EUROPE_ISHARES_UCITS_EXT + ETF_EUROPE_GLOBALX_UCITS + ETF_EUROPE_SPDR_UCITS_EXT +
    ETF_EUROPE_ACC_CORE
))

FONDI_VANGUARD = ['VFIAX', 'VTSAX', 'VBTLX', 'VBLTX', 'VBILX', 'VBIRX', 'VTIAX', 'VWELX', 'VWNDX', 'VIVAX', 'VIGRX', 'VIMSX', 'VSMAX', 'VSCIX', 'VEMAX', 'VPACX', 'VEURX', 'VTRIX', 'VWIGX', 'VGHCX', 'VGENX', 'VQNPX', 'VEXAX', 'VTHRX', 'VFORX', 'VFIFX', 'VFFVX', 'VTINX', 'VTWNX', 'VWUSX', 'VWNFX', 'VMRAX', 'VPMCX']

FONDI_FIDELITY = ['FXAIX', 'FSKAX', 'FSPSX', 'FSMAX', 'FXNAX', 'FZROX', 'FZILX', 'FZIPX', 'FCNTX', 'FDGRX', 'FLPSX', 'FMAGX', 'FBGRX', 'FNCMX', 'FEMKX', 'FIEUX', 'FPADX', 'FIGRX', 'FWWFX', 'FPURX', 'FSCSX', 'FDFAX', 'FSLBX', 'FDVLX', 'FIENX', 'FIGFX', 'FAVFX']

FONDI_TROWE = ['PRWCX', 'PRGFX', 'TRBCX', 'PRNHX', 'RPMGX', 'TRRMX', 'RPSIX', 'RPBAX', 'PRIDX', 'PRITX', 'PRFDX', 'PRSVX', 'PRHSX', 'PRSCX', 'TRMCX', 'PRWAX', 'TRIGX', 'TRAIX']

FONDI_AMERICAN = ['AGTHX', 'AIVSX', 'AMRMX', 'AMCPX', 'AWSHX', 'ANWPX', 'NEWFX', 'AEPGX', 'ABNDX', 'AHITX', 'SMCWX', 'AFIFX', 'ABALX', 'CAIBX', 'CWBFX', 'CIBFX', 'AMFFX']

FONDI_SCHWAB = ['SWPPX', 'SWTSX', 'SWSSX', 'SWMCX', 'SWISX', 'SWAGX', 'SWRSX', 'SWBGX']

FONDI_PIMCO = ['PTTAX', 'PIMIX', 'PFUIX', 'PFORX', 'PHMIX', 'PFLIX', 'PHIYX', 'PLDIX', 'PTLDX', 'PAAIX']

FONDI_DODGECOX = ['DODGX', 'DODIX', 'DODFX', 'DODBX', 'DODWX']

FONDI_DFA = ['DFSVX', 'DFLVX', 'DFUSX', 'DFSCX', 'DFIEX', 'DFIVX', 'DFEMX', 'DFCEX', 'DFLSX', 'DFGEX', 'DFAPX', 'DFGBX']

FONDI_BOUTIQUE = ['OAKMX', 'OAKLX', 'OAKBX', 'SEQUX', 'FAIRX', 'FPACX', 'CGMFX', 'LLPFX', 'JENSX', 'JAMRX', 'JORNX', 'JAENX', 'GABEX', 'YAFFX', 'BRUFX', 'BUFSX', 'TWCUX']

FONDI_FRANKLIN = ['FKINX', 'FKGRX', 'FKDNX', 'FRBSX', 'FREVX', 'FRSGX', 'FCOSX', 'FAVLX', 'FAGIX', 'FCFAX', 'FGNAX', 'FBTAX', 'FGIAX', 'FNBAX', 'FICNX', 'FRHIX', 'FCBFX', 'FLTIX', 'FRGAX', 'FRCAX', 'FRIAX', 'TEPLX', 'TEMFX', 'TGTRX', 'TSIAX', 'TPINX', 'TTRZX', 'TGIFX', 'TFAFX', 'TIGAX', 'TLVAX', 'TGBAX', 'TEFAX', 'MEIAX', 'MUTHX']

FONDI_BLACKROCK_MF = ['BGMAX', 'MDINX', 'MDSCX', 'MDLOX', 'MDDCX', 'MADVX', 'MDFOX', 'MDVAX', 'MEQAX', 'MAHIX', 'MABAX', 'MSMAX', 'BMGAX', 'MDIAX', 'MAIAX']

FONDI_INVESCO_MF = ['OIBAX', 'OPPAX', 'OIGAX', 'OEQAX', 'ACEAX', 'CIVAX', 'IACAX', 'IASGX', 'INVAX']

FONDI_MFS = ['MFQAX', 'MGIAX', 'MMCAX', 'MVRAX', 'MAWAX', 'MIGAX', 'MSSAX', 'MSCAX']

FONDI_PUTNAM = [ 'PGRWX', 'PGVAX', 'PEYAX', 'PELAX', 'PIFAX', 'PINCX', 'PAUAX', 'PTRMX', 'PBLAX', 'PSRAX']

FONDI_COLUMBIA = ['COAGX', 'LACAX', 'NAINX', 'CEOAX', 'CGVAX', 'CLPAX', 'SMGAX', 'CLMAX', 'LDINX', 'CDSAX']

FONDI_JPMORGAN_MF = ['JLVAX', 'OGLAX', 'JGVAX', 'HLQAX', 'OGIAX', 'JIIGX', 'JEMGX', 'HLIAX', 'JSBAX', 'JTNAX', 'JNBAX', 'JIBAX']

FONDI_GOLDMAN_MF = ['GSMAX', 'GSPAX', 'GSGAX', 'GSIAX', 'GSEAX', 'GSFAX', 'GSBAX']

FONDI_LORDABBETT = ['LAFFX', 'LAGAX', 'LAVAX', 'LADAX', 'LBNDX', 'LAIAX', 'LABAX', 'LALDX', 'LMLAX']

FONDI_NEUBERGER = ['NBGNX', 'NEMAX', 'NBIAX', 'NBRAX', 'NBEAX', 'NBBAX', 'NBSAX', 'NBMAX', 'NBHAX']

FONDI_NUVEEN = ['NEIAX', 'NSGAX', 'NMIAX', 'NLSAX', 'NMBAX', 'NHMAX', 'NMAX', 'NIFAX', 'NCLAX', 'NRIAX']

FONDI_TIAA = ['TISPX', 'TIINX', 'TILGX', 'TCREX', 'TCCLX', 'TCLHX', 'TCSEX', 'TCMDX', 'TCEVX', 'TCBRX', 'TIREX', 'TLREX']

FONDI_HARBOR = ['HACAX', 'HRCAX', 'HAIRX', 'HSMVX', 'HCAIX', 'HABDX', 'HNTIX', 'HIINX', 'HGRIX']

FONDI_EATON_VANCE = ['EVTMX', 'EITAX', 'EVTAX', 'EITMX', 'EVGAX', 'EVICX', 'EIUTX', 'EBOAX', 'EBADX', 'EMIAX', 'EAIAX', 'ESMAX']

FONDI_HARTFORD = ['HFMAX', 'HDVAX', 'HSSAX', 'HCVAX', 'HGIAX', 'HIADX', 'HIIGX', 'ITHAX', 'HBAGX', 'HBLAX']

FONDI_JOHN_HANCOCK = ['JHUAX', 'JHQAX', 'JHBGX', 'JHLAX', 'JHINX', 'JHEAX', 'JHTAX', 'JHCAX']

FONDI_ARTISAN = ['ARTMX', 'ARTSX', 'ARTGX', 'ARTJX', 'ARTTX', 'ARTYX', 'ARTLX', 'ARTNX', 'ARTOSX']

FONDI_PARNASSUS = ['PARNX', 'PARWX', 'PARMX', 'PFPLX', 'PRBLX']

FONDI_WASATCH = ['WASAX', 'WASGX', 'WAEMX', 'WMICX', 'WAAEX', 'WAGEX', 'WSCVX', 'FMIEX', 'WHOSX']

FONDI_ROYCE = ['RYOAX', 'RYVPX', 'RYMHX', 'RYFNX', 'RYSHX', 'RYOFX', 'RYREX', 'RMEAX', 'RYCAX', 'RVVAX']

FONDI_THORNBURG = ['THVAX', 'THIFX', 'TIBAX', 'THLAX', 'THCAX', 'THINX', 'THGAX']

FONDI_FIRST_EAGLE = ['SGENX', 'FEGIX', 'FEVAX', 'FEGOX', 'FEGRX', 'FEAIX']

FONDI_MANNING = ['EXDAX', 'MNBRX', 'MNDFX', 'MNDVX', 'MNBAX', 'MNWAX', 'MNNAX']

FONDI_ARIEL = ['ARGFX', 'ARAIX', 'ARFFX', 'ARICX', 'ARIAX', 'ARGAX']

FONDI_BROWN = ['BIAUX', 'BAGMX', 'BASCX', 'BAFVX', 'BIAGX', 'BAISX']

FONDI_MERIDIAN = ['MERDX', 'MVALX', 'MERFX', 'MERGX', 'MERNX']

FONDI_BAIRD = ['BGORX', 'BAGSX', 'BATMX', 'BGFSX', 'BAGGX', 'BAITX']

FONDI_BARON = ['BGRFX', 'BSCFX', 'BGAFX', 'BFTHX', 'BPTRX']

FONDI_MATTHEWS = ['MCHFX', 'MAVRX', 'MAFSX', 'MCEFX', 'MJFOX']

FONDI_PRIMECAP = ['POAGX', 'POGSX', 'POSKX']

FONDI_WEITZ = ['WVALX', 'WPBFX', 'WGRNX', 'WBALX']

FONDI_LOOMIS = ['LSBRX', 'LGMAX']

FONDI_THIRD_AVENUE = ['TAVFX', 'TVSVX', 'TAREX']

FONDI_CHAMPLAIN = ['CIPVX', 'CHIMX']


FONDI_AMERICAN_CENTURY = ['TWMIX', 'TWIEX', 'TWGSX', 'ACINX', 'ACGLX', 'ACEVX', 'ACIDX', 'ACBVX', 'ACNVX', 'ACWSX', 'TWRIX', 'TWVAX', 'TWDIX', 'ACLVX', 'TWBIX']

FONDI_JANUS = ['JGMAX', 'JABAX', 'JAWWX', 'JCPAX', 'JNTRX', 'JAGTX', 'JANWX', 'JADAX', 'JACAX', 'JGRMX', 'JANSX', 'JARIX', 'JAGLX', 'JDCAX', 'JAOAX']

FONDI_CALAMOS = ['CVTRX', 'CVGRX', 'CAGMX', 'CVAAX', 'CIGCX', 'CTFAX', 'CMNAX', 'CNWGX', 'CGHAX', 'CFRAX', 'CBAX', 'CGCAX', 'CLMAX', 'CGWAX']

FONDI_PRINCIPAL = ['PERAX', 'PLBAX', 'PEMAX', 'PMGAX', 'PBDAX', 'PGEAX', 'PPLEX', 'PNPAX', 'PFLEX', 'PRLAX', 'PCBAX', 'PMIAX', 'PSMIX']

FONDI_COHEN_STEERS = ['CSRSX', 'CSFAX', 'CPXAX', 'CSPSX', 'CSLIX', 'CSLAX', 'CSHAX', 'CSGAX', 'CSBAX']

FONDI_TCW = ['TGHNX', 'TGCNX', 'TGLAX', 'TGINX', 'TGOVX', 'TGREX', 'TGBAX', 'TCRIX', 'TGHYX']

FONDI_LEGG_MASON = ['LMOPX', 'WATFX', 'LMASX', 'LMVTX', 'WACSX', 'WAMCX', 'WAOPX', 'WACOX', 'LMDAX', 'LGTRX', 'LMTRX', 'WABSX']

FONDI_NATIXIS = ['NEFAX', 'NEOAX', 'NGIAX', 'NGBAX', 'NHMRX', 'NECOX', 'NEFSX', 'NEFBX', 'NHPAX', 'NUSAX']

FONDI_VIRTUS = ['PHSTX', 'PSNAX', 'STVAX', 'SSIFX', 'VVPAX', 'VMVAX', 'VFMIX', 'DHLAX', 'VGMAX', 'VSMAX', 'VSGAX', 'VITAX']

FONDI_GABELLI_EXT = ['GABCX', 'GABGX', 'GADCX', 'GAMCX', 'GAWAX', 'GASFX', 'GAGEX', 'GABSX', 'GAGAX', 'GABVX']

FONDI_CALVERT = ['CSXAX', 'CSIEX', 'CCFAX', 'CWVGX', 'CEYAX', 'CTAFX', 'CGBAX', 'CSRAX', 'CBALX', 'CBSAX']

FONDI_HENNESSY = ['HFCSX', 'HENLX', 'HICSX', 'HFMCX', 'HFNAX', 'HJPIX', 'HMSFX']

FONDI_AQR = ['AQRIX', 'AQRFX', 'AQMNX', 'AQVNX', 'AQMAX', 'AQSIX', 'AQTIX', 'AQDSX', 'AQMIX', 'AQENX']

FONDI_FIDELITY_SELECT = ['FSELX', 'FSPHX', 'FBIOX', 'FSRFX', 'FSAGX', 'FSMEX', 'FRESX', 'FSENX', 'FSPTX', 'FBSOX', 'FSUTX', 'FSHOX', 'FSDAX', 'FSCHX', 'FSCPX', 'FSCGX', 'FSAIX', 'FCNTX', 'FSLEX', 'FSTCX']

FONDI_TROWE_EXT = ['PTEBX', 'PRFHX', 'TGLMX', 'TRBAX', 'PRTAX', 'PRESX', 'PAEMX', 'TRMRX', 'PRUKX', 'TRPDX', 'PRCPX', 'PRZIX', 'PRLAX', 'PRJPX']

FONDI_FEDERATED = ['FKIAX', 'FGKAX', 'FLIAX', 'FEQAX', 'FSTAX', 'FLGAX', 'FGIAX']

FONDI_COLUMBIA_EXT = ['CTRZX', 'CMGAX', 'CMVAX', 'CMOAX', 'CBSAX', 'CCORX', 'CSPAX', 'COMVX', 'CQSAX', 'CTLAX']

FONDI_DELAWARE = ['DEMAX', 'DBIAX', 'DFCAX', 'DITAX', 'DBCAX', 'DPIGX', 'DEDAX', 'DTIAX', 'DIQAX', 'DVAAX']

FONDI_INVESCO_EXT = ['ACMVX', 'INVNX', 'IVPAX', 'IVQAX', 'IVINX', 'IVASX', 'INVGX', 'IVEFX', 'CCSAX', 'CCVAX']

FONDI_WELLS_FARGO = ['WFVAX', 'WFOVX', 'SGDAX', 'WFUAX', 'WFHAX', 'WFBAX', 'WFGAX', 'WFIAX', 'WFEAX', 'WFCAX', 'WFAUX']

FONDI_AMERICAN_BEACON = ['AAFAX', 'ABRGX', 'ABLAX', 'ABAUX', 'ABOAX', 'ABNAX', 'ABRAX', 'ABSGX', 'ABMAX', 'ABLUX']

FONDI_VICTORY = ['VRSAX', 'VRCAX', 'VRGAX', 'VRMAX', 'VETAX', 'VESAX', 'VCVHX', 'VSMSX', 'VGRAX', 'VSCIX']

FONDI_FRANKLIN_EXT = ['FTAAX', 'FCAAX', 'FIFAX', 'FRCAX', 'FGSAX', 'FKAAX', 'FISAX', 'FTSAX', 'FAGAX', 'FALAX', 'FAUAX', 'FAVAX', 'FAMGX', 'FANAX', 'FARAX']

FONDI_VANGUARD_EXT = ['VWITX', 'VWLTX', 'VWSTX', 'VHYAX', 'VCITX', 'VFSTX', 'VFSUX', 'VBIRX', 'VBLAX', 'VCSHX', 'VPGDX', 'VEIPX', 'VDIGX', 'VHGEX', 'VGWLX']

FONDI_SCHWAB_EXT = ['SWLSX', 'SWHEX', 'SWNGX', 'SWIVX', 'SWGSX', 'SWKSX', 'SWVSX', 'SWTIX', 'SWVDX', 'SWVIX', 'SWIAX']

FONDI_LOOMIS_EXT = ['LSGSX', 'LSIGX', 'LSIIX', 'LGMAX', 'LSGIX', 'LGMYX', 'LSZAX', 'LSEIX']

FONDI_NATIONWIDE = ['NWJLX', 'NWGAX', 'NWMAX', 'NWBAX', 'NWIAX', 'NWVAX', 'NWCAX', 'NWDAX', 'NWEAX']

FONDI_SENTINEL = ['SENCX', 'SENAAX', 'SENIX', 'SENBX', 'SENGX', 'SENAX', 'SESMX']

FONDI_MESIROW = ['MFCAX', 'MFHAX', 'MFMAX']

FONDI_PERRITT = ['PRCGX', 'PRESX', 'PRMSX', 'PRGGX']

FONDI_KELLSTROM = ['KCMTX', 'KAUAX', 'KMDAX']

# ── ESPANSIONE US (aggiunto 2026-06-20) ───────────────────────────────────────

FONDI_AB = [
    'AGDAX', 'ABHYX', 'ABNAX', 'ABIAX', 'CHPAX', 'CHPIX', 'ABSCX',
    'ABYZX', 'ABGLX', 'ACENX', 'ABLDX', 'ABLVX', 'ABTWX', 'ABTYX',
    'ABWAX', 'ACFNX', 'ACSIX', 'ABMIX', 'ALNAX']

FONDI_PGIM = [
    'PJPAX', 'PJPZX', 'PJIAX', 'PJIIX', 'PBDAX', 'PBDZX', 'PSNAX',
    'PSNZX', 'PJGAX', 'PJHAX', 'PHYAX', 'PGFAX', 'PGEAX',
    'PDVAX', 'PDVIX', 'PJLAX', 'PGHAX', 'PMMZX']

FONDI_MORGAN_STANLEY = [
    'MSEGX', 'MSEQX', 'MSIQX', 'MSNZX', 'MSSSX', 'MSUAX', 'MSOAX',
    'MSDPX', 'MSCTX', 'MPEGX', 'MPEAX', 'MSOCX', 'MSVIX',
    'MSFAX', 'MSFBX', 'MSPAX', 'MSWVX', 'MSGIX']

FONDI_STATE_STREET_MF = [
    'SVSPX', 'SSIRX', 'SSIMX', 'SSIEX', 'SSBRX', 'SVSCX',
    'SSAJX', 'SSOFX', 'SSIAX', 'SSRIX', 'SSSYX', 'SSCOX']

FONDI_WILLIAM_BLAIR = [
    'WBGSX', 'WBLNX', 'WBIGX', 'WBSMX', 'WBMMX', 'WBMDX', 'WBKIX',
    'WBSAX', 'WBIFX', 'WBCLX', 'WBEIX', 'WBMIX', 'WBTNX', 'WBEGX']

FONDI_CAUSEWAY = [
    'CIVIX', 'CIVVX', 'CEMIX', 'CEMVX', 'CFVAX', 'CGGAX', 'CGVAX',
    'CGLVX', 'CGIEX', 'CSIIX', 'CSIVX']

FONDI_HOTCHKIS = [
    'HWMAX', 'HWMIX', 'HWSIX', 'HWSAX', 'HWLIX', 'HWLAX', 'HWSCX',
    'HWVAX', 'HWVIX', 'HWEIX', 'HWBAX', 'HWBIX']

FONDI_ALGER = [
    'ALGFX', 'ALMAX', 'ALGAX', 'ALGNX', 'ALSAX', 'ALMCX', 'ALFAX',
    'ALVAX', 'ALSZX', 'ALGIX', 'ALDAX', 'ALDIX', 'ALIAX']

FONDI_TRANSAMERICA = [
    'TAGOX', 'TACOX', 'TBGAX', 'TABVX', 'TAITX', 'TAUOX', 'TAPAX',
    'TASRX', 'TSMIX', 'TSLAX', 'TSIAX', 'TAVZX', 'TGWAX', 'TLRIX']

# ALL_FONDI: aggiornato con nuove famiglie US (2026-06-20)
ALL_FONDI = list(dict.fromkeys(
    FONDI_VANGUARD + FONDI_FIDELITY + FONDI_TROWE + FONDI_AMERICAN + FONDI_SCHWAB + FONDI_PIMCO + FONDI_DODGECOX + FONDI_DFA + FONDI_BOUTIQUE + FONDI_FRANKLIN + FONDI_BLACKROCK_MF + FONDI_INVESCO_MF + FONDI_MFS + FONDI_PUTNAM + FONDI_COLUMBIA + FONDI_JPMORGAN_MF + FONDI_GOLDMAN_MF + FONDI_LORDABBETT + FONDI_NEUBERGER + FONDI_NUVEEN + FONDI_TIAA + FONDI_HARBOR + FONDI_EATON_VANCE + FONDI_HARTFORD + FONDI_JOHN_HANCOCK + FONDI_ARTISAN + FONDI_PARNASSUS + FONDI_WASATCH + FONDI_ROYCE + FONDI_THORNBURG + FONDI_FIRST_EAGLE + FONDI_MANNING + FONDI_ARIEL + FONDI_BROWN + FONDI_MERIDIAN + FONDI_BAIRD + FONDI_BARON + FONDI_MATTHEWS + FONDI_PRIMECAP + FONDI_WEITZ + FONDI_LOOMIS + FONDI_THIRD_AVENUE + FONDI_CHAMPLAIN + FONDI_AMERICAN_CENTURY + FONDI_JANUS + FONDI_CALAMOS + FONDI_PRINCIPAL + FONDI_COHEN_STEERS + FONDI_TCW + FONDI_LEGG_MASON + FONDI_NATIXIS + FONDI_VIRTUS + FONDI_GABELLI_EXT + FONDI_CALVERT + FONDI_HENNESSY + FONDI_AQR + FONDI_FIDELITY_SELECT + FONDI_TROWE_EXT + FONDI_FEDERATED + FONDI_COLUMBIA_EXT + FONDI_DELAWARE + FONDI_INVESCO_EXT + FONDI_WELLS_FARGO + FONDI_AMERICAN_BEACON + FONDI_VICTORY + FONDI_FRANKLIN_EXT + FONDI_VANGUARD_EXT + FONDI_SCHWAB_EXT + FONDI_LOOMIS_EXT + FONDI_NATIONWIDE + FONDI_SENTINEL + FONDI_MESIROW + FONDI_PERRITT
    # nuove famiglie US
    + FONDI_AB + FONDI_PGIM + FONDI_MORGAN_STANLEY + FONDI_STATE_STREET_MF
    + FONDI_WILLIAM_BLAIR + FONDI_CAUSEWAY + FONDI_HOTCHKIS + FONDI_ALGER + FONDI_TRANSAMERICA
))

if __name__ == "__main__":
    print(f"Azioni: {len(ALL_AZIONI)} | ETF: {len(ALL_ETF)} | Fondi: {len(ALL_FONDI)}")